# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/MercuryXU1_NuPRISM.xdc

# Block Designs: bd/MercuryXU1/MercuryXU1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1 || ORIG_REF_NAME==MercuryXU1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xbar_1/MercuryXU1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xbar_1 || ORIG_REF_NAME==MercuryXU1_xbar_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_ps8_0_axi_periph_0/MercuryXU1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_ps8_0_axi_periph_0 || ORIG_REF_NAME==MercuryXU1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/MercuryXU1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_smc_0 || ORIG_REF_NAME==MercuryXU1_axi_smc_0} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/bd_cc23.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_0/bd_cc23_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_1/bd_cc23_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_2/bd_cc23_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_3/bd_cc23_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_4/bd_cc23_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_5/bd_cc23_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_6/bd_cc23_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_7/bd_cc23_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_8/bd_cc23_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_9/bd_cc23_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_10/bd_cc23_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_11/bd_cc23_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_12/bd_cc23_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_13/bd_cc23_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_14/bd_cc23_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_15/bd_cc23_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_16/bd_cc23_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_17/bd_cc23_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_18/bd_cc23_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_19/bd_cc23_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_20/bd_cc23_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_21/bd_cc23_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_22/bd_cc23_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_23/bd_cc23_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_24/bd_cc23_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_25/bd_cc23_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_26/bd_cc23_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_27/bd_cc23_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_28/bd_cc23_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_29/bd_cc23_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconcat_0_0/MercuryXU1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconcat_0_0 || ORIG_REF_NAME==MercuryXU1_xlconcat_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_0_0/MercuryXU1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_data_fifo_0_0 || ORIG_REF_NAME==MercuryXU1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_3_0/MercuryXU1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_3_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_3_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_4_0/MercuryXU1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_4_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_4_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_5_0/MercuryXU1_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_5_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_5_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_0/MercuryXU1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_0 || ORIG_REF_NAME==MercuryXU1_auto_pc_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_1/MercuryXU1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_1 || ORIG_REF_NAME==MercuryXU1_auto_pc_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_2/MercuryXU1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_2 || ORIG_REF_NAME==MercuryXU1_auto_pc_2} -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_xbar_1/MercuryXU1_xbar_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_1/bd_cc23_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_1/bd_cc23_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_2/bd_cc23_arsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_3/bd_cc23_rsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_4/bd_cc23_awsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_5/bd_cc23_wsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_6/bd_cc23_bsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_10/bd_cc23_s00a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_11/bd_cc23_sarn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_12/bd_cc23_srn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_13/bd_cc23_sawn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_14/bd_cc23_swn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_15/bd_cc23_sbn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_19/bd_cc23_s02a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_20/bd_cc23_sawn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_21/bd_cc23_swn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_22/bd_cc23_sbn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_23/bd_cc23_m00s2a_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_24/bd_cc23_m00arn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_25/bd_cc23_m00rn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_26/bd_cc23_m00awn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_27/bd_cc23_m00wn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/bd_0/ip/ip_28/bd_cc23_m00bn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_0_0/MercuryXU1_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_auto_pc_0/MercuryXU1_auto_pc_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_auto_pc_1/MercuryXU1_auto_pc_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_auto_pc_2/MercuryXU1_auto_pc_2_ooc.xdc

# XDC: bd/MercuryXU1/MercuryXU1_ooc.xdc
