# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/MercuryXU1_NuPRISM.xdc

# Block Designs: bd/MercuryXU1/MercuryXU1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1 || ORIG_REF_NAME==MercuryXU1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xbar_1/MercuryXU1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xbar_1 || ORIG_REF_NAME==MercuryXU1_xbar_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_ps8_0_axi_periph_0/MercuryXU1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_ps8_0_axi_periph_0 || ORIG_REF_NAME==MercuryXU1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_smc_0/MercuryXU1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_smc_0 || ORIG_REF_NAME==MercuryXU1_axi_smc_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconcat_0_0/MercuryXU1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconcat_0_0 || ORIG_REF_NAME==MercuryXU1_xlconcat_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_0_0/MercuryXU1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_data_fifo_0_0 || ORIG_REF_NAME==MercuryXU1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_3_0/MercuryXU1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_3_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_3_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_4_0/MercuryXU1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_4_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_4_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconstant_5_0/MercuryXU1_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconstant_5_0 || ORIG_REF_NAME==MercuryXU1_xlconstant_5_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_0/MercuryXU1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_0 || ORIG_REF_NAME==MercuryXU1_auto_pc_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_1/MercuryXU1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_1 || ORIG_REF_NAME==MercuryXU1_auto_pc_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_2/MercuryXU1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_2 || ORIG_REF_NAME==MercuryXU1_auto_pc_2} -quiet] -quiet

# XDC: bd/MercuryXU1/MercuryXU1_ooc.xdc
