/******************************************************************************
*
* (c) Copyright 2014-15 Xilinx, Inc. All rights reserved.
*
* This file contains confidential and proprietary information of Xilinx, Inc.
* and is protected under U.S. and international copyright and other
* intellectual property laws.
*
* DISCLAIMER
* This disclaimer is not a license and does not grant any rights to the
* materials distributed herewith. Except as otherwise provided in a valid
* license issued to you by Xilinx, and to the maximum extent permitted by
* applicable law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL
* FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS,
* IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
* MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE;
* and (2) Xilinx shall not be liable (whether in contract or tort, including
* negligence, or under any other theory of liability) for any loss or damage
* of any kind or nature related to, arising under or in connection with these
* materials, including for any direct, or any indirect, special, incidental,
* or consequential loss or damage (including loss of data, profits, goodwill,
* or any type of loss or damage suffered as a result of any action brought by
* a third party) even if such damage or loss was reasonably foreseeable or
* Xilinx had been advised of the possibility of the same.
*
* CRITICAL APPLICATIONS
* Xilinx products are not designed or intended to be fail-safe, or for use in
* any application requiring fail-safe performance, such as life-support or
* safety devices or systems, Class III medical devices, nuclear facilities,
* applications related to the deployment of airbags, or any other applications
* that could lead to death, personal injury, or severe property or
* environmental damage (individually and collectively, "Critical
* Applications"). Customer assumes the sole risk and liability of any use of
* Xilinx products in Critical Applications, subject only to applicable laws
* and regulations governing limitations on product liability.
*
* THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE
* AT ALL TIMES.
*
******************************************************************************/
/*****************************************************************************/
/**
*
* @file csu.h
*
* This is CSU header file. Containing all the register addresses.
*
* @note 	This is a script generated file.
*
*
* Date Created : 
*
******************************************************************************/

#ifndef __CSU_H__
#define __CSU_H__

#ifdef __cplusplus
	extern "C"
	#endif
		
		
#define CSU_BASEADDRESS	0xFFCA0000

/* CSU_STATUS REGISTER */ 
#define CSU_CSU_STATUS	0xFFCA0000
#define CSU_CSU_STATUS_DEFVAL	0x0
#define CSU_CSU_STATUS_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_STATUS_UNUSED_LSB_OFFSET	 2 
#define CSU_CSU_STATUS_UNUSED_WIDTH	30
#define CSU_CSU_STATUS_UNUSED_DEFVAL	0x0
#define CSU_CSU_STATUS_UNUSED_MASK	 0xFFFFFFFC 

#define CSU_CSU_STATUS_BOOT_ENC_LSB_OFFSET	 1 
#define CSU_CSU_STATUS_BOOT_ENC_WIDTH	1
#define CSU_CSU_STATUS_BOOT_ENC_DEFVAL	0x0
#define CSU_CSU_STATUS_BOOT_ENC_MASK	 0x2 

#define CSU_CSU_STATUS_BOOT_AUTH_LSB_OFFSET	 0 
#define CSU_CSU_STATUS_BOOT_AUTH_WIDTH	1
#define CSU_CSU_STATUS_BOOT_AUTH_DEFVAL	0x0
#define CSU_CSU_STATUS_BOOT_AUTH_MASK	 0x1 


/* CSU_CTRL REGISTER */ 
#define CSU_CSU_CTRL	0xFFCA0004
#define CSU_CSU_CTRL_DEFVAL	0x0
#define CSU_CSU_CTRL_CMP_MASK	0x1F
#define CSU_CSU_CTRL_SLVERR_ENABLE_LSB_OFFSET	 4 
#define CSU_CSU_CTRL_SLVERR_ENABLE_WIDTH	1
#define CSU_CSU_CTRL_SLVERR_ENABLE_DEFVAL	0x0
#define CSU_CSU_CTRL_SLVERR_ENABLE_MASK	 0x10 

#define CSU_CSU_CTRL_CSU_CLK_SEL_LSB_OFFSET	 0 
#define CSU_CSU_CTRL_CSU_CLK_SEL_WIDTH	1
#define CSU_CSU_CTRL_CSU_CLK_SEL_DEFVAL	0x0
#define CSU_CSU_CTRL_CSU_CLK_SEL_MASK	 0x1 


/* CSU_SSS_CFG REGISTER */ 
#define CSU_CSU_SSS_CFG	0xFFCA0008
#define CSU_CSU_SSS_CFG_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_CMP_MASK	0xFFFFF
#define CSU_CSU_SSS_CFG_PSTP_SSS_LSB_OFFSET	 16 
#define CSU_CSU_SSS_CFG_PSTP_SSS_WIDTH	4
#define CSU_CSU_SSS_CFG_PSTP_SSS_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_PSTP_SSS_MASK	 0xF0000 

#define CSU_CSU_SSS_CFG_SHA_SSS_LSB_OFFSET	 12 
#define CSU_CSU_SSS_CFG_SHA_SSS_WIDTH	4
#define CSU_CSU_SSS_CFG_SHA_SSS_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_SHA_SSS_MASK	 0xF000 

#define CSU_CSU_SSS_CFG_AES_SSS_LSB_OFFSET	 8 
#define CSU_CSU_SSS_CFG_AES_SSS_WIDTH	4
#define CSU_CSU_SSS_CFG_AES_SSS_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_AES_SSS_MASK	 0xF00 

#define CSU_CSU_SSS_CFG_DMA_SSS_LSB_OFFSET	 4 
#define CSU_CSU_SSS_CFG_DMA_SSS_WIDTH	4
#define CSU_CSU_SSS_CFG_DMA_SSS_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_DMA_SSS_MASK	 0xF0 

#define CSU_CSU_SSS_CFG_PCAP_SSS_LSB_OFFSET	 0 
#define CSU_CSU_SSS_CFG_PCAP_SSS_WIDTH	4
#define CSU_CSU_SSS_CFG_PCAP_SSS_DEFVAL	0x0
#define CSU_CSU_SSS_CFG_PCAP_SSS_MASK	 0xF 


/* CSU_DMA_RESET REGISTER */ 
#define CSU_CSU_DMA_RESET	0xFFCA000C
#define CSU_CSU_DMA_RESET_DEFVAL	0x0
#define CSU_CSU_DMA_RESET_CMP_MASK	0x1
#define CSU_CSU_DMA_RESET_RESET_LSB_OFFSET	 0 
#define CSU_CSU_DMA_RESET_RESET_WIDTH	1
#define CSU_CSU_DMA_RESET_RESET_DEFVAL	0x0
#define CSU_CSU_DMA_RESET_RESET_MASK	 0x1 


/* CSU_MULTI_BOOT REGISTER */ 
#define CSU_CSU_MULTI_BOOT	0xFFCA0010
#define CSU_CSU_MULTI_BOOT_DEFVAL	0x0
#define CSU_CSU_MULTI_BOOT_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_MULTI_BOOT_SSSS_MULTI_BOOT_ADDR_LSB_OFFSET	 0 
#define CSU_CSU_MULTI_BOOT_SSSS_MULTI_BOOT_ADDR_WIDTH	32
#define CSU_CSU_MULTI_BOOT_SSSS_MULTI_BOOT_ADDR_DEFVAL	0x0
#define CSU_CSU_MULTI_BOOT_SSSS_MULTI_BOOT_ADDR_MASK	 0xFFFFFFFF 


/* CSU_TAMPER_TRIG REGISTER */ 
#define CSU_CSU_TAMPER_TRIG	0xFFCA0014
#define CSU_CSU_TAMPER_TRIG_DEFVAL	0x0
#define CSU_CSU_TAMPER_TRIG_CMP_MASK	0x1
#define CSU_CSU_TAMPER_TRIG_TAMPER_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_TRIG_TAMPER_WIDTH	1
#define CSU_CSU_TAMPER_TRIG_TAMPER_DEFVAL	0x0
#define CSU_CSU_TAMPER_TRIG_TAMPER_MASK	 0x1 


/* CSU_FT_STATUS REGISTER */ 
#define CSU_CSU_FT_STATUS	0xFFCA0018
#define CSU_CSU_FT_STATUS_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_FT_STATUS_R_UE_LSB_OFFSET	 31 
#define CSU_CSU_FT_STATUS_R_UE_WIDTH	1
#define CSU_CSU_FT_STATUS_R_UE_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_UE_MASK	 0x80000000 

#define CSU_CSU_FT_STATUS_R_VOTER_ERROR_LSB_OFFSET	 30 
#define CSU_CSU_FT_STATUS_R_VOTER_ERROR_WIDTH	1
#define CSU_CSU_FT_STATUS_R_VOTER_ERROR_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_VOTER_ERROR_MASK	 0x40000000 

#define CSU_CSU_FT_STATUS_R_COMP_ERR_23_LSB_OFFSET	 29 
#define CSU_CSU_FT_STATUS_R_COMP_ERR_23_WIDTH	1
#define CSU_CSU_FT_STATUS_R_COMP_ERR_23_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_COMP_ERR_23_MASK	 0x20000000 

#define CSU_CSU_FT_STATUS_R_COMP_ERR_13_LSB_OFFSET	 28 
#define CSU_CSU_FT_STATUS_R_COMP_ERR_13_WIDTH	1
#define CSU_CSU_FT_STATUS_R_COMP_ERR_13_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_COMP_ERR_13_MASK	 0x10000000 

#define CSU_CSU_FT_STATUS_R_COMP_ERR_12_LSB_OFFSET	 27 
#define CSU_CSU_FT_STATUS_R_COMP_ERR_12_WIDTH	1
#define CSU_CSU_FT_STATUS_R_COMP_ERR_12_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_COMP_ERR_12_MASK	 0x8000000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_23_A_LSB_OFFSET	 26 
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_A_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_A_MASK	 0x4000000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_13_A_LSB_OFFSET	 25 
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_A_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_A_MASK	 0x2000000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_12_A_LSB_OFFSET	 24 
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_A_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_A_MASK	 0x1000000 

#define CSU_CSU_FT_STATUS_R_FT_ST_MISMATCH_LSB_OFFSET	 23 
#define CSU_CSU_FT_STATUS_R_FT_ST_MISMATCH_WIDTH	1
#define CSU_CSU_FT_STATUS_R_FT_ST_MISMATCH_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_FT_ST_MISMATCH_MASK	 0x800000 

#define CSU_CSU_FT_STATUS_R_CPU_ID_MISMATCH_LSB_OFFSET	 22 
#define CSU_CSU_FT_STATUS_R_CPU_ID_MISMATCH_WIDTH	1
#define CSU_CSU_FT_STATUS_R_CPU_ID_MISMATCH_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_CPU_ID_MISMATCH_MASK	 0x400000 

#define CSU_CSU_FT_STATUS_R_SLEEP_RESET_LSB_OFFSET	 19 
#define CSU_CSU_FT_STATUS_R_SLEEP_RESET_WIDTH	1
#define CSU_CSU_FT_STATUS_R_SLEEP_RESET_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_SLEEP_RESET_MASK	 0x80000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_23_B_LSB_OFFSET	 18 
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_B_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_23_B_MASK	 0x40000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_13_B_LSB_OFFSET	 17 
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_B_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_13_B_MASK	 0x20000 

#define CSU_CSU_FT_STATUS_R_MISMATCH_12_B_LSB_OFFSET	 16 
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_B_WIDTH	1
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_R_MISMATCH_12_B_MASK	 0x10000 

#define CSU_CSU_FT_STATUS_N_UE_LSB_OFFSET	 15 
#define CSU_CSU_FT_STATUS_N_UE_WIDTH	1
#define CSU_CSU_FT_STATUS_N_UE_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_UE_MASK	 0x8000 

#define CSU_CSU_FT_STATUS_N_VOTER_ERROR_LSB_OFFSET	 14 
#define CSU_CSU_FT_STATUS_N_VOTER_ERROR_WIDTH	1
#define CSU_CSU_FT_STATUS_N_VOTER_ERROR_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_VOTER_ERROR_MASK	 0x4000 

#define CSU_CSU_FT_STATUS_N_COMP_ERR_23_LSB_OFFSET	 13 
#define CSU_CSU_FT_STATUS_N_COMP_ERR_23_WIDTH	1
#define CSU_CSU_FT_STATUS_N_COMP_ERR_23_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_COMP_ERR_23_MASK	 0x2000 

#define CSU_CSU_FT_STATUS_N_COMP_ERR_13_LSB_OFFSET	 12 
#define CSU_CSU_FT_STATUS_N_COMP_ERR_13_WIDTH	1
#define CSU_CSU_FT_STATUS_N_COMP_ERR_13_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_COMP_ERR_13_MASK	 0x1000 

#define CSU_CSU_FT_STATUS_N_COMP_ERR_12_LSB_OFFSET	 11 
#define CSU_CSU_FT_STATUS_N_COMP_ERR_12_WIDTH	1
#define CSU_CSU_FT_STATUS_N_COMP_ERR_12_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_COMP_ERR_12_MASK	 0x800 

#define CSU_CSU_FT_STATUS_N_MISMATCH_23_A_LSB_OFFSET	 10 
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_A_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_A_MASK	 0x400 

#define CSU_CSU_FT_STATUS_N_MISMATCH_13_A_LSB_OFFSET	 9 
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_A_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_A_MASK	 0x200 

#define CSU_CSU_FT_STATUS_N_MISMATCH_12_A_LSB_OFFSET	 8 
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_A_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_A_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_A_MASK	 0x100 

#define CSU_CSU_FT_STATUS_N_FT_ST_MISMATCH_LSB_OFFSET	 7 
#define CSU_CSU_FT_STATUS_N_FT_ST_MISMATCH_WIDTH	1
#define CSU_CSU_FT_STATUS_N_FT_ST_MISMATCH_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_FT_ST_MISMATCH_MASK	 0x80 

#define CSU_CSU_FT_STATUS_N_CPU_ID_MISMATCH_LSB_OFFSET	 6 
#define CSU_CSU_FT_STATUS_N_CPU_ID_MISMATCH_WIDTH	1
#define CSU_CSU_FT_STATUS_N_CPU_ID_MISMATCH_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_CPU_ID_MISMATCH_MASK	 0x40 

#define CSU_CSU_FT_STATUS_N_SLEEP_RESET_LSB_OFFSET	 3 
#define CSU_CSU_FT_STATUS_N_SLEEP_RESET_WIDTH	1
#define CSU_CSU_FT_STATUS_N_SLEEP_RESET_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_SLEEP_RESET_MASK	 0x8 

#define CSU_CSU_FT_STATUS_N_MISMATCH_23_B_LSB_OFFSET	 2 
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_B_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_23_B_MASK	 0x4 

#define CSU_CSU_FT_STATUS_N_MISMATCH_13_B_LSB_OFFSET	 1 
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_B_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_13_B_MASK	 0x2 

#define CSU_CSU_FT_STATUS_N_MISMATCH_12_B_LSB_OFFSET	 0 
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_B_WIDTH	1
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_B_DEFVAL	0x0
#define CSU_CSU_FT_STATUS_N_MISMATCH_12_B_MASK	 0x1 


/* CSU_ISR REGISTER */ 
#define CSU_CSU_ISR	0xFFCA0020
#define CSU_CSU_ISR_DEFVAL	0x0
#define CSU_CSU_ISR_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ISR_UNUSED31_LSB_OFFSET	 31 
#define CSU_CSU_ISR_UNUSED31_WIDTH	1
#define CSU_CSU_ISR_UNUSED31_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED31_MASK	 0x80000000 

#define CSU_CSU_ISR_UNUSED30_LSB_OFFSET	 30 
#define CSU_CSU_ISR_UNUSED30_WIDTH	1
#define CSU_CSU_ISR_UNUSED30_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED30_MASK	 0x40000000 

#define CSU_CSU_ISR_UNUSED29_LSB_OFFSET	 29 
#define CSU_CSU_ISR_UNUSED29_WIDTH	1
#define CSU_CSU_ISR_UNUSED29_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED29_MASK	 0x20000000 

#define CSU_CSU_ISR_UNUSED28_LSB_OFFSET	 28 
#define CSU_CSU_ISR_UNUSED28_WIDTH	1
#define CSU_CSU_ISR_UNUSED28_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED28_MASK	 0x10000000 

#define CSU_CSU_ISR_UNUSED27_LSB_OFFSET	 27 
#define CSU_CSU_ISR_UNUSED27_WIDTH	1
#define CSU_CSU_ISR_UNUSED27_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED27_MASK	 0x8000000 

#define CSU_CSU_ISR_UNUSED26_LSB_OFFSET	 26 
#define CSU_CSU_ISR_UNUSED26_WIDTH	1
#define CSU_CSU_ISR_UNUSED26_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED26_MASK	 0x4000000 

#define CSU_CSU_ISR_UNUSED25_LSB_OFFSET	 25 
#define CSU_CSU_ISR_UNUSED25_WIDTH	1
#define CSU_CSU_ISR_UNUSED25_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED25_MASK	 0x2000000 

#define CSU_CSU_ISR_UNUSED24_LSB_OFFSET	 24 
#define CSU_CSU_ISR_UNUSED24_WIDTH	1
#define CSU_CSU_ISR_UNUSED24_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED24_MASK	 0x1000000 

#define CSU_CSU_ISR_UNUSED23_LSB_OFFSET	 23 
#define CSU_CSU_ISR_UNUSED23_WIDTH	1
#define CSU_CSU_ISR_UNUSED23_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED23_MASK	 0x800000 

#define CSU_CSU_ISR_UNUSED22_LSB_OFFSET	 22 
#define CSU_CSU_ISR_UNUSED22_WIDTH	1
#define CSU_CSU_ISR_UNUSED22_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED22_MASK	 0x400000 

#define CSU_CSU_ISR_UNUSED21_LSB_OFFSET	 21 
#define CSU_CSU_ISR_UNUSED21_WIDTH	1
#define CSU_CSU_ISR_UNUSED21_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED21_MASK	 0x200000 

#define CSU_CSU_ISR_UNUSED20_LSB_OFFSET	 20 
#define CSU_CSU_ISR_UNUSED20_WIDTH	1
#define CSU_CSU_ISR_UNUSED20_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED20_MASK	 0x100000 

#define CSU_CSU_ISR_UNUSED19_LSB_OFFSET	 19 
#define CSU_CSU_ISR_UNUSED19_WIDTH	1
#define CSU_CSU_ISR_UNUSED19_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED19_MASK	 0x80000 

#define CSU_CSU_ISR_UNUSED18_LSB_OFFSET	 18 
#define CSU_CSU_ISR_UNUSED18_WIDTH	1
#define CSU_CSU_ISR_UNUSED18_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED18_MASK	 0x40000 

#define CSU_CSU_ISR_UNUSED17_LSB_OFFSET	 17 
#define CSU_CSU_ISR_UNUSED17_WIDTH	1
#define CSU_CSU_ISR_UNUSED17_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED17_MASK	 0x20000 

#define CSU_CSU_ISR_UNUSED16_LSB_OFFSET	 16 
#define CSU_CSU_ISR_UNUSED16_WIDTH	1
#define CSU_CSU_ISR_UNUSED16_DEFVAL	0x0
#define CSU_CSU_ISR_UNUSED16_MASK	 0x10000 

#define CSU_CSU_ISR_CSU_PL_ISO_LSB_OFFSET	 15 
#define CSU_CSU_ISR_CSU_PL_ISO_WIDTH	1
#define CSU_CSU_ISR_CSU_PL_ISO_DEFVAL	0x0
#define CSU_CSU_ISR_CSU_PL_ISO_MASK	 0x8000 

#define CSU_CSU_ISR_CSU_RAM_ECC_ERROR_LSB_OFFSET	 14 
#define CSU_CSU_ISR_CSU_RAM_ECC_ERROR_WIDTH	1
#define CSU_CSU_ISR_CSU_RAM_ECC_ERROR_DEFVAL	0x0
#define CSU_CSU_ISR_CSU_RAM_ECC_ERROR_MASK	 0x4000 

#define CSU_CSU_ISR_TAMPER_LSB_OFFSET	 13 
#define CSU_CSU_ISR_TAMPER_WIDTH	1
#define CSU_CSU_ISR_TAMPER_DEFVAL	0x0
#define CSU_CSU_ISR_TAMPER_MASK	 0x2000 

#define CSU_CSU_ISR_PUF_ACC_ERROR_LSB_OFFSET	 12 
#define CSU_CSU_ISR_PUF_ACC_ERROR_WIDTH	1
#define CSU_CSU_ISR_PUF_ACC_ERROR_DEFVAL	0x0
#define CSU_CSU_ISR_PUF_ACC_ERROR_MASK	 0x1000 

#define CSU_CSU_ISR_APB_SLVERR_LSB_OFFSET	 11 
#define CSU_CSU_ISR_APB_SLVERR_WIDTH	1
#define CSU_CSU_ISR_APB_SLVERR_DEFVAL	0x0
#define CSU_CSU_ISR_APB_SLVERR_MASK	 0x800 

#define CSU_CSU_ISR_TMR_FATAL_LSB_OFFSET	 10 
#define CSU_CSU_ISR_TMR_FATAL_WIDTH	1
#define CSU_CSU_ISR_TMR_FATAL_DEFVAL	0x0
#define CSU_CSU_ISR_TMR_FATAL_MASK	 0x400 

#define CSU_CSU_ISR_PL_SEU_ERROR_LSB_OFFSET	 9 
#define CSU_CSU_ISR_PL_SEU_ERROR_WIDTH	1
#define CSU_CSU_ISR_PL_SEU_ERROR_DEFVAL	0x0
#define CSU_CSU_ISR_PL_SEU_ERROR_MASK	 0x200 

#define CSU_CSU_ISR_AES_ERROR_LSB_OFFSET	 8 
#define CSU_CSU_ISR_AES_ERROR_WIDTH	1
#define CSU_CSU_ISR_AES_ERROR_DEFVAL	0x0
#define CSU_CSU_ISR_AES_ERROR_MASK	 0x100 

#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_LSB_OFFSET	 7 
#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_WIDTH	1
#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_MASK	 0x80 

#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_LSB_OFFSET	 6 
#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_WIDTH	1
#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_MASK	 0x40 

#define CSU_CSU_ISR_PL_POR_B_LSB_OFFSET	 5 
#define CSU_CSU_ISR_PL_POR_B_WIDTH	1
#define CSU_CSU_ISR_PL_POR_B_DEFVAL	0x0
#define CSU_CSU_ISR_PL_POR_B_MASK	 0x20 

#define CSU_CSU_ISR_PL_INIT_LSB_OFFSET	 4 
#define CSU_CSU_ISR_PL_INIT_WIDTH	1
#define CSU_CSU_ISR_PL_INIT_DEFVAL	0x0
#define CSU_CSU_ISR_PL_INIT_MASK	 0x10 

#define CSU_CSU_ISR_PL_DONE_LSB_OFFSET	 3 
#define CSU_CSU_ISR_PL_DONE_WIDTH	1
#define CSU_CSU_ISR_PL_DONE_DEFVAL	0x0
#define CSU_CSU_ISR_PL_DONE_MASK	 0x8 

#define CSU_CSU_ISR_SHA_DONE_LSB_OFFSET	 2 
#define CSU_CSU_ISR_SHA_DONE_WIDTH	1
#define CSU_CSU_ISR_SHA_DONE_DEFVAL	0x0
#define CSU_CSU_ISR_SHA_DONE_MASK	 0x4 

#define CSU_CSU_ISR_RSA_DONE_LSB_OFFSET	 1 
#define CSU_CSU_ISR_RSA_DONE_WIDTH	1
#define CSU_CSU_ISR_RSA_DONE_DEFVAL	0x0
#define CSU_CSU_ISR_RSA_DONE_MASK	 0x2 

#define CSU_CSU_ISR_AES_DONE_LSB_OFFSET	 0 
#define CSU_CSU_ISR_AES_DONE_WIDTH	1
#define CSU_CSU_ISR_AES_DONE_DEFVAL	0x0
#define CSU_CSU_ISR_AES_DONE_MASK	 0x1 


/* CSU_IMR REGISTER */ 
#define CSU_CSU_IMR	0xFFCA0024
#define CSU_CSU_IMR_DEFVAL	0xFFFFFFFF
#define CSU_CSU_IMR_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_IMR_UNUSED31_LSB_OFFSET	 31 
#define CSU_CSU_IMR_UNUSED31_WIDTH	1
#define CSU_CSU_IMR_UNUSED31_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED31_MASK	 0x80000000 

#define CSU_CSU_IMR_UNUSED30_LSB_OFFSET	 30 
#define CSU_CSU_IMR_UNUSED30_WIDTH	1
#define CSU_CSU_IMR_UNUSED30_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED30_MASK	 0x40000000 

#define CSU_CSU_IMR_UNUSED29_LSB_OFFSET	 29 
#define CSU_CSU_IMR_UNUSED29_WIDTH	1
#define CSU_CSU_IMR_UNUSED29_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED29_MASK	 0x20000000 

#define CSU_CSU_IMR_UNUSED28_LSB_OFFSET	 28 
#define CSU_CSU_IMR_UNUSED28_WIDTH	1
#define CSU_CSU_IMR_UNUSED28_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED28_MASK	 0x10000000 

#define CSU_CSU_IMR_UNUSED27_LSB_OFFSET	 27 
#define CSU_CSU_IMR_UNUSED27_WIDTH	1
#define CSU_CSU_IMR_UNUSED27_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED27_MASK	 0x8000000 

#define CSU_CSU_IMR_UNUSED26_LSB_OFFSET	 26 
#define CSU_CSU_IMR_UNUSED26_WIDTH	1
#define CSU_CSU_IMR_UNUSED26_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED26_MASK	 0x4000000 

#define CSU_CSU_IMR_UNUSED25_LSB_OFFSET	 25 
#define CSU_CSU_IMR_UNUSED25_WIDTH	1
#define CSU_CSU_IMR_UNUSED25_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED25_MASK	 0x2000000 

#define CSU_CSU_IMR_UNUSED24_LSB_OFFSET	 24 
#define CSU_CSU_IMR_UNUSED24_WIDTH	1
#define CSU_CSU_IMR_UNUSED24_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED24_MASK	 0x1000000 

#define CSU_CSU_IMR_UNUSED23_LSB_OFFSET	 23 
#define CSU_CSU_IMR_UNUSED23_WIDTH	1
#define CSU_CSU_IMR_UNUSED23_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED23_MASK	 0x800000 

#define CSU_CSU_IMR_UNUSED22_LSB_OFFSET	 22 
#define CSU_CSU_IMR_UNUSED22_WIDTH	1
#define CSU_CSU_IMR_UNUSED22_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED22_MASK	 0x400000 

#define CSU_CSU_IMR_UNUSED21_LSB_OFFSET	 21 
#define CSU_CSU_IMR_UNUSED21_WIDTH	1
#define CSU_CSU_IMR_UNUSED21_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED21_MASK	 0x200000 

#define CSU_CSU_IMR_UNUSED20_LSB_OFFSET	 20 
#define CSU_CSU_IMR_UNUSED20_WIDTH	1
#define CSU_CSU_IMR_UNUSED20_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED20_MASK	 0x100000 

#define CSU_CSU_IMR_UNUSED19_LSB_OFFSET	 19 
#define CSU_CSU_IMR_UNUSED19_WIDTH	1
#define CSU_CSU_IMR_UNUSED19_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED19_MASK	 0x80000 

#define CSU_CSU_IMR_UNUSED18_LSB_OFFSET	 18 
#define CSU_CSU_IMR_UNUSED18_WIDTH	1
#define CSU_CSU_IMR_UNUSED18_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED18_MASK	 0x40000 

#define CSU_CSU_IMR_UNUSED17_LSB_OFFSET	 17 
#define CSU_CSU_IMR_UNUSED17_WIDTH	1
#define CSU_CSU_IMR_UNUSED17_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED17_MASK	 0x20000 

#define CSU_CSU_IMR_UNUSED16_LSB_OFFSET	 16 
#define CSU_CSU_IMR_UNUSED16_WIDTH	1
#define CSU_CSU_IMR_UNUSED16_DEFVAL	0x1
#define CSU_CSU_IMR_UNUSED16_MASK	 0x10000 

#define CSU_CSU_IMR_CSU_PL_ISO_LSB_OFFSET	 15 
#define CSU_CSU_IMR_CSU_PL_ISO_WIDTH	1
#define CSU_CSU_IMR_CSU_PL_ISO_DEFVAL	0x1
#define CSU_CSU_IMR_CSU_PL_ISO_MASK	 0x8000 

#define CSU_CSU_IMR_CSU_RAM_ECC_ERROR_LSB_OFFSET	 14 
#define CSU_CSU_IMR_CSU_RAM_ECC_ERROR_WIDTH	1
#define CSU_CSU_IMR_CSU_RAM_ECC_ERROR_DEFVAL	0x1
#define CSU_CSU_IMR_CSU_RAM_ECC_ERROR_MASK	 0x4000 

#define CSU_CSU_IMR_TAMPER_LSB_OFFSET	 13 
#define CSU_CSU_IMR_TAMPER_WIDTH	1
#define CSU_CSU_IMR_TAMPER_DEFVAL	0x1
#define CSU_CSU_IMR_TAMPER_MASK	 0x2000 

#define CSU_CSU_IMR_PUF_ACC_ERROR_LSB_OFFSET	 12 
#define CSU_CSU_IMR_PUF_ACC_ERROR_WIDTH	1
#define CSU_CSU_IMR_PUF_ACC_ERROR_DEFVAL	0x1
#define CSU_CSU_IMR_PUF_ACC_ERROR_MASK	 0x1000 

#define CSU_CSU_IMR_APB_SLVERR_LSB_OFFSET	 11 
#define CSU_CSU_IMR_APB_SLVERR_WIDTH	1
#define CSU_CSU_IMR_APB_SLVERR_DEFVAL	0x1
#define CSU_CSU_IMR_APB_SLVERR_MASK	 0x800 

#define CSU_CSU_IMR_TMR_FATAL_LSB_OFFSET	 10 
#define CSU_CSU_IMR_TMR_FATAL_WIDTH	1
#define CSU_CSU_IMR_TMR_FATAL_DEFVAL	0x1
#define CSU_CSU_IMR_TMR_FATAL_MASK	 0x400 

#define CSU_CSU_IMR_PL_SEU_ERROR_LSB_OFFSET	 9 
#define CSU_CSU_IMR_PL_SEU_ERROR_WIDTH	1
#define CSU_CSU_IMR_PL_SEU_ERROR_DEFVAL	0x1
#define CSU_CSU_IMR_PL_SEU_ERROR_MASK	 0x200 

#define CSU_CSU_IMR_AES_ERROR_LSB_OFFSET	 8 
#define CSU_CSU_IMR_AES_ERROR_WIDTH	1
#define CSU_CSU_IMR_AES_ERROR_DEFVAL	0x1
#define CSU_CSU_IMR_AES_ERROR_MASK	 0x100 

#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_LSB_OFFSET	 7 
#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_WIDTH	1
#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_DEFVAL	0x1
#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_MASK	 0x80 

#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_LSB_OFFSET	 6 
#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_WIDTH	1
#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_DEFVAL	0x1
#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_MASK	 0x40 

#define CSU_CSU_IMR_PL_POR_B_LSB_OFFSET	 5 
#define CSU_CSU_IMR_PL_POR_B_WIDTH	1
#define CSU_CSU_IMR_PL_POR_B_DEFVAL	0x1
#define CSU_CSU_IMR_PL_POR_B_MASK	 0x20 

#define CSU_CSU_IMR_PL_INIT_LSB_OFFSET	 4 
#define CSU_CSU_IMR_PL_INIT_WIDTH	1
#define CSU_CSU_IMR_PL_INIT_DEFVAL	0x1
#define CSU_CSU_IMR_PL_INIT_MASK	 0x10 

#define CSU_CSU_IMR_PL_DONE_LSB_OFFSET	 3 
#define CSU_CSU_IMR_PL_DONE_WIDTH	1
#define CSU_CSU_IMR_PL_DONE_DEFVAL	0x1
#define CSU_CSU_IMR_PL_DONE_MASK	 0x8 

#define CSU_CSU_IMR_SHA_DONE_LSB_OFFSET	 2 
#define CSU_CSU_IMR_SHA_DONE_WIDTH	1
#define CSU_CSU_IMR_SHA_DONE_DEFVAL	0x1
#define CSU_CSU_IMR_SHA_DONE_MASK	 0x4 

#define CSU_CSU_IMR_RSA_DONE_LSB_OFFSET	 1 
#define CSU_CSU_IMR_RSA_DONE_WIDTH	1
#define CSU_CSU_IMR_RSA_DONE_DEFVAL	0x1
#define CSU_CSU_IMR_RSA_DONE_MASK	 0x2 

#define CSU_CSU_IMR_AES_DONE_LSB_OFFSET	 0 
#define CSU_CSU_IMR_AES_DONE_WIDTH	1
#define CSU_CSU_IMR_AES_DONE_DEFVAL	0x1
#define CSU_CSU_IMR_AES_DONE_MASK	 0x1 


/* CSU_IER REGISTER */ 
#define CSU_CSU_IER	0xFFCA0028
#define CSU_CSU_IER_DEFVAL	0x0
#define CSU_CSU_IER_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_IER_UNUSED31_LSB_OFFSET	 31 
#define CSU_CSU_IER_UNUSED31_WIDTH	1
#define CSU_CSU_IER_UNUSED31_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED31_MASK	 0x80000000 

#define CSU_CSU_IER_UNUSED30_LSB_OFFSET	 30 
#define CSU_CSU_IER_UNUSED30_WIDTH	1
#define CSU_CSU_IER_UNUSED30_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED30_MASK	 0x40000000 

#define CSU_CSU_IER_UNUSED29_LSB_OFFSET	 29 
#define CSU_CSU_IER_UNUSED29_WIDTH	1
#define CSU_CSU_IER_UNUSED29_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED29_MASK	 0x20000000 

#define CSU_CSU_IER_UNUSED28_LSB_OFFSET	 28 
#define CSU_CSU_IER_UNUSED28_WIDTH	1
#define CSU_CSU_IER_UNUSED28_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED28_MASK	 0x10000000 

#define CSU_CSU_IER_UNUSED27_LSB_OFFSET	 27 
#define CSU_CSU_IER_UNUSED27_WIDTH	1
#define CSU_CSU_IER_UNUSED27_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED27_MASK	 0x8000000 

#define CSU_CSU_IER_UNUSED26_LSB_OFFSET	 26 
#define CSU_CSU_IER_UNUSED26_WIDTH	1
#define CSU_CSU_IER_UNUSED26_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED26_MASK	 0x4000000 

#define CSU_CSU_IER_UNUSED25_LSB_OFFSET	 25 
#define CSU_CSU_IER_UNUSED25_WIDTH	1
#define CSU_CSU_IER_UNUSED25_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED25_MASK	 0x2000000 

#define CSU_CSU_IER_UNUSED24_LSB_OFFSET	 24 
#define CSU_CSU_IER_UNUSED24_WIDTH	1
#define CSU_CSU_IER_UNUSED24_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED24_MASK	 0x1000000 

#define CSU_CSU_IER_UNUSED23_LSB_OFFSET	 23 
#define CSU_CSU_IER_UNUSED23_WIDTH	1
#define CSU_CSU_IER_UNUSED23_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED23_MASK	 0x800000 

#define CSU_CSU_IER_UNUSED22_LSB_OFFSET	 22 
#define CSU_CSU_IER_UNUSED22_WIDTH	1
#define CSU_CSU_IER_UNUSED22_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED22_MASK	 0x400000 

#define CSU_CSU_IER_UNUSED21_LSB_OFFSET	 21 
#define CSU_CSU_IER_UNUSED21_WIDTH	1
#define CSU_CSU_IER_UNUSED21_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED21_MASK	 0x200000 

#define CSU_CSU_IER_UNUSED20_LSB_OFFSET	 20 
#define CSU_CSU_IER_UNUSED20_WIDTH	1
#define CSU_CSU_IER_UNUSED20_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED20_MASK	 0x100000 

#define CSU_CSU_IER_UNUSED19_LSB_OFFSET	 19 
#define CSU_CSU_IER_UNUSED19_WIDTH	1
#define CSU_CSU_IER_UNUSED19_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED19_MASK	 0x80000 

#define CSU_CSU_IER_UNUSED18_LSB_OFFSET	 18 
#define CSU_CSU_IER_UNUSED18_WIDTH	1
#define CSU_CSU_IER_UNUSED18_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED18_MASK	 0x40000 

#define CSU_CSU_IER_UNUSED17_LSB_OFFSET	 17 
#define CSU_CSU_IER_UNUSED17_WIDTH	1
#define CSU_CSU_IER_UNUSED17_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED17_MASK	 0x20000 

#define CSU_CSU_IER_UNUSED16_LSB_OFFSET	 16 
#define CSU_CSU_IER_UNUSED16_WIDTH	1
#define CSU_CSU_IER_UNUSED16_DEFVAL	0x0
#define CSU_CSU_IER_UNUSED16_MASK	 0x10000 

#define CSU_CSU_IER_CSU_PL_ISO_LSB_OFFSET	 15 
#define CSU_CSU_IER_CSU_PL_ISO_WIDTH	1
#define CSU_CSU_IER_CSU_PL_ISO_DEFVAL	0x0
#define CSU_CSU_IER_CSU_PL_ISO_MASK	 0x8000 

#define CSU_CSU_IER_CSU_RAM_ECC_ERROR_LSB_OFFSET	 14 
#define CSU_CSU_IER_CSU_RAM_ECC_ERROR_WIDTH	1
#define CSU_CSU_IER_CSU_RAM_ECC_ERROR_DEFVAL	0x0
#define CSU_CSU_IER_CSU_RAM_ECC_ERROR_MASK	 0x4000 

#define CSU_CSU_IER_TAMPER_LSB_OFFSET	 13 
#define CSU_CSU_IER_TAMPER_WIDTH	1
#define CSU_CSU_IER_TAMPER_DEFVAL	0x0
#define CSU_CSU_IER_TAMPER_MASK	 0x2000 

#define CSU_CSU_IER_PUF_ACC_ERROR_LSB_OFFSET	 12 
#define CSU_CSU_IER_PUF_ACC_ERROR_WIDTH	1
#define CSU_CSU_IER_PUF_ACC_ERROR_DEFVAL	0x0
#define CSU_CSU_IER_PUF_ACC_ERROR_MASK	 0x1000 

#define CSU_CSU_IER_APB_SLVERR_LSB_OFFSET	 11 
#define CSU_CSU_IER_APB_SLVERR_WIDTH	1
#define CSU_CSU_IER_APB_SLVERR_DEFVAL	0x0
#define CSU_CSU_IER_APB_SLVERR_MASK	 0x800 

#define CSU_CSU_IER_TMR_FATAL_LSB_OFFSET	 10 
#define CSU_CSU_IER_TMR_FATAL_WIDTH	1
#define CSU_CSU_IER_TMR_FATAL_DEFVAL	0x0
#define CSU_CSU_IER_TMR_FATAL_MASK	 0x400 

#define CSU_CSU_IER_PL_SEU_ERROR_LSB_OFFSET	 9 
#define CSU_CSU_IER_PL_SEU_ERROR_WIDTH	1
#define CSU_CSU_IER_PL_SEU_ERROR_DEFVAL	0x0
#define CSU_CSU_IER_PL_SEU_ERROR_MASK	 0x200 

#define CSU_CSU_IER_AES_ERROR_LSB_OFFSET	 8 
#define CSU_CSU_IER_AES_ERROR_WIDTH	1
#define CSU_CSU_IER_AES_ERROR_DEFVAL	0x0
#define CSU_CSU_IER_AES_ERROR_MASK	 0x100 

#define CSU_CSU_IER_PCAP_WR_OVERFLOW_LSB_OFFSET	 7 
#define CSU_CSU_IER_PCAP_WR_OVERFLOW_WIDTH	1
#define CSU_CSU_IER_PCAP_WR_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_IER_PCAP_WR_OVERFLOW_MASK	 0x80 

#define CSU_CSU_IER_PCAP_RD_OVERFLOW_LSB_OFFSET	 6 
#define CSU_CSU_IER_PCAP_RD_OVERFLOW_WIDTH	1
#define CSU_CSU_IER_PCAP_RD_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_IER_PCAP_RD_OVERFLOW_MASK	 0x40 

#define CSU_CSU_IER_PL_POR_B_LSB_OFFSET	 5 
#define CSU_CSU_IER_PL_POR_B_WIDTH	1
#define CSU_CSU_IER_PL_POR_B_DEFVAL	0x0
#define CSU_CSU_IER_PL_POR_B_MASK	 0x20 

#define CSU_CSU_IER_PL_INIT_LSB_OFFSET	 4 
#define CSU_CSU_IER_PL_INIT_WIDTH	1
#define CSU_CSU_IER_PL_INIT_DEFVAL	0x0
#define CSU_CSU_IER_PL_INIT_MASK	 0x10 

#define CSU_CSU_IER_PL_DONE_LSB_OFFSET	 3 
#define CSU_CSU_IER_PL_DONE_WIDTH	1
#define CSU_CSU_IER_PL_DONE_DEFVAL	0x0
#define CSU_CSU_IER_PL_DONE_MASK	 0x8 

#define CSU_CSU_IER_SHA_DONE_LSB_OFFSET	 2 
#define CSU_CSU_IER_SHA_DONE_WIDTH	1
#define CSU_CSU_IER_SHA_DONE_DEFVAL	0x0
#define CSU_CSU_IER_SHA_DONE_MASK	 0x4 

#define CSU_CSU_IER_RSA_DONE_LSB_OFFSET	 1 
#define CSU_CSU_IER_RSA_DONE_WIDTH	1
#define CSU_CSU_IER_RSA_DONE_DEFVAL	0x0
#define CSU_CSU_IER_RSA_DONE_MASK	 0x2 

#define CSU_CSU_IER_AES_DONE_LSB_OFFSET	 0 
#define CSU_CSU_IER_AES_DONE_WIDTH	1
#define CSU_CSU_IER_AES_DONE_DEFVAL	0x0
#define CSU_CSU_IER_AES_DONE_MASK	 0x1 


/* CSU_IDR REGISTER */ 
#define CSU_CSU_IDR	0xFFCA002C
#define CSU_CSU_IDR_DEFVAL	0x0
#define CSU_CSU_IDR_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_IDR_UNUSED31_LSB_OFFSET	 31 
#define CSU_CSU_IDR_UNUSED31_WIDTH	1
#define CSU_CSU_IDR_UNUSED31_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED31_MASK	 0x80000000 

#define CSU_CSU_IDR_UNUSED30_LSB_OFFSET	 30 
#define CSU_CSU_IDR_UNUSED30_WIDTH	1
#define CSU_CSU_IDR_UNUSED30_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED30_MASK	 0x40000000 

#define CSU_CSU_IDR_UNUSED29_LSB_OFFSET	 29 
#define CSU_CSU_IDR_UNUSED29_WIDTH	1
#define CSU_CSU_IDR_UNUSED29_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED29_MASK	 0x20000000 

#define CSU_CSU_IDR_UNUSED28_LSB_OFFSET	 28 
#define CSU_CSU_IDR_UNUSED28_WIDTH	1
#define CSU_CSU_IDR_UNUSED28_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED28_MASK	 0x10000000 

#define CSU_CSU_IDR_UNUSED27_LSB_OFFSET	 27 
#define CSU_CSU_IDR_UNUSED27_WIDTH	1
#define CSU_CSU_IDR_UNUSED27_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED27_MASK	 0x8000000 

#define CSU_CSU_IDR_UNUSED26_LSB_OFFSET	 26 
#define CSU_CSU_IDR_UNUSED26_WIDTH	1
#define CSU_CSU_IDR_UNUSED26_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED26_MASK	 0x4000000 

#define CSU_CSU_IDR_UNUSED25_LSB_OFFSET	 25 
#define CSU_CSU_IDR_UNUSED25_WIDTH	1
#define CSU_CSU_IDR_UNUSED25_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED25_MASK	 0x2000000 

#define CSU_CSU_IDR_UNUSED24_LSB_OFFSET	 24 
#define CSU_CSU_IDR_UNUSED24_WIDTH	1
#define CSU_CSU_IDR_UNUSED24_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED24_MASK	 0x1000000 

#define CSU_CSU_IDR_UNUSED23_LSB_OFFSET	 23 
#define CSU_CSU_IDR_UNUSED23_WIDTH	1
#define CSU_CSU_IDR_UNUSED23_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED23_MASK	 0x800000 

#define CSU_CSU_IDR_UNUSED22_LSB_OFFSET	 22 
#define CSU_CSU_IDR_UNUSED22_WIDTH	1
#define CSU_CSU_IDR_UNUSED22_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED22_MASK	 0x400000 

#define CSU_CSU_IDR_UNUSED21_LSB_OFFSET	 21 
#define CSU_CSU_IDR_UNUSED21_WIDTH	1
#define CSU_CSU_IDR_UNUSED21_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED21_MASK	 0x200000 

#define CSU_CSU_IDR_UNUSED20_LSB_OFFSET	 20 
#define CSU_CSU_IDR_UNUSED20_WIDTH	1
#define CSU_CSU_IDR_UNUSED20_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED20_MASK	 0x100000 

#define CSU_CSU_IDR_UNUSED19_LSB_OFFSET	 19 
#define CSU_CSU_IDR_UNUSED19_WIDTH	1
#define CSU_CSU_IDR_UNUSED19_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED19_MASK	 0x80000 

#define CSU_CSU_IDR_UNUSED18_LSB_OFFSET	 18 
#define CSU_CSU_IDR_UNUSED18_WIDTH	1
#define CSU_CSU_IDR_UNUSED18_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED18_MASK	 0x40000 

#define CSU_CSU_IDR_UNUSED17_LSB_OFFSET	 17 
#define CSU_CSU_IDR_UNUSED17_WIDTH	1
#define CSU_CSU_IDR_UNUSED17_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED17_MASK	 0x20000 

#define CSU_CSU_IDR_UNUSED16_LSB_OFFSET	 16 
#define CSU_CSU_IDR_UNUSED16_WIDTH	1
#define CSU_CSU_IDR_UNUSED16_DEFVAL	0x0
#define CSU_CSU_IDR_UNUSED16_MASK	 0x10000 

#define CSU_CSU_IDR_CSU_PL_ISO_LSB_OFFSET	 15 
#define CSU_CSU_IDR_CSU_PL_ISO_WIDTH	1
#define CSU_CSU_IDR_CSU_PL_ISO_DEFVAL	0x0
#define CSU_CSU_IDR_CSU_PL_ISO_MASK	 0x8000 

#define CSU_CSU_IDR_CSU_RAM_ECC_ERROR_LSB_OFFSET	 14 
#define CSU_CSU_IDR_CSU_RAM_ECC_ERROR_WIDTH	1
#define CSU_CSU_IDR_CSU_RAM_ECC_ERROR_DEFVAL	0x0
#define CSU_CSU_IDR_CSU_RAM_ECC_ERROR_MASK	 0x4000 

#define CSU_CSU_IDR_TAMPER_LSB_OFFSET	 13 
#define CSU_CSU_IDR_TAMPER_WIDTH	1
#define CSU_CSU_IDR_TAMPER_DEFVAL	0x0
#define CSU_CSU_IDR_TAMPER_MASK	 0x2000 

#define CSU_CSU_IDR_PUF_ACC_ERROR_LSB_OFFSET	 12 
#define CSU_CSU_IDR_PUF_ACC_ERROR_WIDTH	1
#define CSU_CSU_IDR_PUF_ACC_ERROR_DEFVAL	0x0
#define CSU_CSU_IDR_PUF_ACC_ERROR_MASK	 0x1000 

#define CSU_CSU_IDR_APB_SLVERR_LSB_OFFSET	 11 
#define CSU_CSU_IDR_APB_SLVERR_WIDTH	1
#define CSU_CSU_IDR_APB_SLVERR_DEFVAL	0x0
#define CSU_CSU_IDR_APB_SLVERR_MASK	 0x800 

#define CSU_CSU_IDR_TMR_FATAL_LSB_OFFSET	 10 
#define CSU_CSU_IDR_TMR_FATAL_WIDTH	1
#define CSU_CSU_IDR_TMR_FATAL_DEFVAL	0x0
#define CSU_CSU_IDR_TMR_FATAL_MASK	 0x400 

#define CSU_CSU_IDR_PL_SEU_ERROR_LSB_OFFSET	 9 
#define CSU_CSU_IDR_PL_SEU_ERROR_WIDTH	1
#define CSU_CSU_IDR_PL_SEU_ERROR_DEFVAL	0x0
#define CSU_CSU_IDR_PL_SEU_ERROR_MASK	 0x200 

#define CSU_CSU_IDR_AES_ERROR_LSB_OFFSET	 8 
#define CSU_CSU_IDR_AES_ERROR_WIDTH	1
#define CSU_CSU_IDR_AES_ERROR_DEFVAL	0x0
#define CSU_CSU_IDR_AES_ERROR_MASK	 0x100 

#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_LSB_OFFSET	 7 
#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_WIDTH	1
#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_MASK	 0x80 

#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_LSB_OFFSET	 6 
#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_WIDTH	1
#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_DEFVAL	0x0
#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_MASK	 0x40 

#define CSU_CSU_IDR_PL_POR_B_LSB_OFFSET	 5 
#define CSU_CSU_IDR_PL_POR_B_WIDTH	1
#define CSU_CSU_IDR_PL_POR_B_DEFVAL	0x0
#define CSU_CSU_IDR_PL_POR_B_MASK	 0x20 

#define CSU_CSU_IDR_PL_INIT_LSB_OFFSET	 4 
#define CSU_CSU_IDR_PL_INIT_WIDTH	1
#define CSU_CSU_IDR_PL_INIT_DEFVAL	0x0
#define CSU_CSU_IDR_PL_INIT_MASK	 0x10 

#define CSU_CSU_IDR_PL_DONE_LSB_OFFSET	 3 
#define CSU_CSU_IDR_PL_DONE_WIDTH	1
#define CSU_CSU_IDR_PL_DONE_DEFVAL	0x0
#define CSU_CSU_IDR_PL_DONE_MASK	 0x8 

#define CSU_CSU_IDR_SHA_DONE_LSB_OFFSET	 2 
#define CSU_CSU_IDR_SHA_DONE_WIDTH	1
#define CSU_CSU_IDR_SHA_DONE_DEFVAL	0x0
#define CSU_CSU_IDR_SHA_DONE_MASK	 0x4 

#define CSU_CSU_IDR_RSA_DONE_LSB_OFFSET	 1 
#define CSU_CSU_IDR_RSA_DONE_WIDTH	1
#define CSU_CSU_IDR_RSA_DONE_DEFVAL	0x0
#define CSU_CSU_IDR_RSA_DONE_MASK	 0x2 

#define CSU_CSU_IDR_AES_DONE_LSB_OFFSET	 0 
#define CSU_CSU_IDR_AES_DONE_WIDTH	1
#define CSU_CSU_IDR_AES_DONE_DEFVAL	0x0
#define CSU_CSU_IDR_AES_DONE_MASK	 0x1 


/* JTAG_CHAIN_CFG REGISTER */ 
#define CSU_JTAG_CHAIN_CFG	0xFFCA0030
#define CSU_JTAG_CHAIN_CFG_DEFVAL	0x0
#define CSU_JTAG_CHAIN_CFG_CMP_MASK	0x3
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_ARM_DAP_LSB_OFFSET	 1 
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_ARM_DAP_WIDTH	1
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_ARM_DAP_DEFVAL	0x0
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_ARM_DAP_MASK	 0x2 

#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_PL_TAP_LSB_OFFSET	 0 
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_PL_TAP_WIDTH	1
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_PL_TAP_DEFVAL	0x0
#define CSU_JTAG_CHAIN_CFG_SSSS_LINK_PL_TAP_MASK	 0x1 


/* JTAG_CHAIN_STATUS REGISTER */ 
#define CSU_JTAG_CHAIN_STATUS	0xFFCA0034
#define CSU_JTAG_CHAIN_STATUS_DEFVAL	0x0
#define CSU_JTAG_CHAIN_STATUS_CMP_MASK	0x3
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_LSB_OFFSET	 1 
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_WIDTH	1
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_DEFVAL	0x0
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_MASK	 0x2 

#define CSU_JTAG_CHAIN_STATUS_PL_TAP_LSB_OFFSET	 0 
#define CSU_JTAG_CHAIN_STATUS_PL_TAP_WIDTH	1
#define CSU_JTAG_CHAIN_STATUS_PL_TAP_DEFVAL	0x0
#define CSU_JTAG_CHAIN_STATUS_PL_TAP_MASK	 0x1 


/* JTAG_SEC REGISTER */ 
#define CSU_JTAG_SEC	0xFFCA0038
#define CSU_JTAG_SEC_DEFVAL	0x0
#define CSU_JTAG_SEC_CMP_MASK	0x7FFF
#define CSU_JTAG_SEC_SSSS_DDRPHY_SEC_LSB_OFFSET	 12 
#define CSU_JTAG_SEC_SSSS_DDRPHY_SEC_WIDTH	3
#define CSU_JTAG_SEC_SSSS_DDRPHY_SEC_DEFVAL	0x0
#define CSU_JTAG_SEC_SSSS_DDRPHY_SEC_MASK	 0x7000 

#define CSU_JTAG_SEC_SSSS_PLTAP_EN_LSB_OFFSET	 9 
#define CSU_JTAG_SEC_SSSS_PLTAP_EN_WIDTH	3
#define CSU_JTAG_SEC_SSSS_PLTAP_EN_DEFVAL	0x0
#define CSU_JTAG_SEC_SSSS_PLTAP_EN_MASK	 0xE00 

#define CSU_JTAG_SEC_SSSS_PMU_SEC_LSB_OFFSET	 6 
#define CSU_JTAG_SEC_SSSS_PMU_SEC_WIDTH	3
#define CSU_JTAG_SEC_SSSS_PMU_SEC_DEFVAL	0x0
#define CSU_JTAG_SEC_SSSS_PMU_SEC_MASK	 0x1C0 

#define CSU_JTAG_SEC_SSSS_PLTAP_SEC_LSB_OFFSET	 3 
#define CSU_JTAG_SEC_SSSS_PLTAP_SEC_WIDTH	3
#define CSU_JTAG_SEC_SSSS_PLTAP_SEC_DEFVAL	0x0
#define CSU_JTAG_SEC_SSSS_PLTAP_SEC_MASK	 0x38 

#define CSU_JTAG_SEC_SSSS_DAP_SEC_LSB_OFFSET	 0 
#define CSU_JTAG_SEC_SSSS_DAP_SEC_WIDTH	3
#define CSU_JTAG_SEC_SSSS_DAP_SEC_DEFVAL	0x0
#define CSU_JTAG_SEC_SSSS_DAP_SEC_MASK	 0x7 


/* JTAG_DAP_CFG REGISTER */ 
#define CSU_JTAG_DAP_CFG	0xFFCA003C
#define CSU_JTAG_DAP_CFG_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_CMP_MASK	0xFF
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPNIDEN_LSB_OFFSET	 7 
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPNIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPNIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPNIDEN_MASK	 0x80 

#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPIDEN_LSB_OFFSET	 6 
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_RPU_SPIDEN_MASK	 0x40 

#define CSU_JTAG_DAP_CFG_SSSS_RPU_NIDEN_LSB_OFFSET	 5 
#define CSU_JTAG_DAP_CFG_SSSS_RPU_NIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_RPU_NIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_RPU_NIDEN_MASK	 0x20 

#define CSU_JTAG_DAP_CFG_SSSS_RPU_DBGEN_LSB_OFFSET	 4 
#define CSU_JTAG_DAP_CFG_SSSS_RPU_DBGEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_RPU_DBGEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_RPU_DBGEN_MASK	 0x10 

#define CSU_JTAG_DAP_CFG_SSSS_APU_SPNIDEN_LSB_OFFSET	 3 
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPNIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPNIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPNIDEN_MASK	 0x8 

#define CSU_JTAG_DAP_CFG_SSSS_APU_SPIDEN_LSB_OFFSET	 2 
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_APU_SPIDEN_MASK	 0x4 

#define CSU_JTAG_DAP_CFG_SSSS_APU_NIDEN_LSB_OFFSET	 1 
#define CSU_JTAG_DAP_CFG_SSSS_APU_NIDEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_APU_NIDEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_APU_NIDEN_MASK	 0x2 

#define CSU_JTAG_DAP_CFG_SSSS_APU_DBGEN_LSB_OFFSET	 0 
#define CSU_JTAG_DAP_CFG_SSSS_APU_DBGEN_WIDTH	1
#define CSU_JTAG_DAP_CFG_SSSS_APU_DBGEN_DEFVAL	0x0
#define CSU_JTAG_DAP_CFG_SSSS_APU_DBGEN_MASK	 0x1 


/* IDCODE REGISTER */ 
#define CSU_IDCODE	0xFFCA0040
#define CSU_IDCODE_DEFVAL	0x0
#define CSU_IDCODE_CMP_MASK	0x0
#define CSU_IDCODE_IDCODE_LSB_OFFSET	 0 
#define CSU_IDCODE_IDCODE_WIDTH	32
#define CSU_IDCODE_IDCODE_DEFVAL	0x0
#define CSU_IDCODE_IDCODE_MASK	 0xFFFFFFFF 


/* VERSION REGISTER */ 
#define CSU_VERSION	0xFFCA0044
#define CSU_VERSION_DEFVAL	0x0
#define CSU_VERSION_CMP_MASK	0xFF00F
#define CSU_VERSION_PLATFORM_VERSION_LSB_OFFSET	 16 
#define CSU_VERSION_PLATFORM_VERSION_WIDTH	4
#define CSU_VERSION_PLATFORM_VERSION_DEFVAL	0x0
#define CSU_VERSION_PLATFORM_VERSION_MASK	 0xF0000 

#define CSU_VERSION_PLATFORM_LSB_OFFSET	 12 
#define CSU_VERSION_PLATFORM_WIDTH	4
#define CSU_VERSION_PLATFORM_DEFVAL	0x0
#define CSU_VERSION_PLATFORM_MASK	 0xF000 

#define CSU_VERSION_RTL_VERSION_LSB_OFFSET	 4 
#define CSU_VERSION_RTL_VERSION_WIDTH	8
#define CSU_VERSION_RTL_VERSION_DEFVAL	0x0
#define CSU_VERSION_RTL_VERSION_MASK	 0xFF0 

#define CSU_VERSION_PS_VERSION_LSB_OFFSET	 0 
#define CSU_VERSION_PS_VERSION_WIDTH	4
#define CSU_VERSION_PS_VERSION_DEFVAL	0x0
#define CSU_VERSION_PS_VERSION_MASK	 0xF 


/* CSU_ROM_DIGEST_0 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_0	0xFFCA0050
#define CSU_CSU_ROM_DIGEST_0_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_0_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_0_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_0_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_0_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_0_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_1 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_1	0xFFCA0054
#define CSU_CSU_ROM_DIGEST_1_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_1_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_1_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_1_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_1_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_1_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_2 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_2	0xFFCA0058
#define CSU_CSU_ROM_DIGEST_2_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_2_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_2_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_2_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_2_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_2_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_3 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_3	0xFFCA005C
#define CSU_CSU_ROM_DIGEST_3_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_3_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_3_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_3_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_3_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_3_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_4 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_4	0xFFCA0060
#define CSU_CSU_ROM_DIGEST_4_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_4_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_4_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_4_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_4_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_4_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_5 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_5	0xFFCA0064
#define CSU_CSU_ROM_DIGEST_5_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_5_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_5_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_5_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_5_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_5_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_6 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_6	0xFFCA0068
#define CSU_CSU_ROM_DIGEST_6_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_6_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_6_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_6_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_6_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_6_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_7 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_7	0xFFCA006C
#define CSU_CSU_ROM_DIGEST_7_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_7_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_7_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_7_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_7_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_7_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_8 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_8	0xFFCA0070
#define CSU_CSU_ROM_DIGEST_8_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_8_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_8_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_8_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_8_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_8_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_9 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_9	0xFFCA0074
#define CSU_CSU_ROM_DIGEST_9_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_9_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_9_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_9_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_9_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_9_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_10 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_10	0xFFCA0078
#define CSU_CSU_ROM_DIGEST_10_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_10_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_10_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_10_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_10_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_10_DIGEST_MASK	 0xFFFFFFFF 


/* CSU_ROM_DIGEST_11 REGISTER */ 
#define CSU_CSU_ROM_DIGEST_11	0xFFCA007C
#define CSU_CSU_ROM_DIGEST_11_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_11_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_11_DIGEST_LSB_OFFSET	 0 
#define CSU_CSU_ROM_DIGEST_11_DIGEST_WIDTH	32
#define CSU_CSU_ROM_DIGEST_11_DIGEST_DEFVAL	0xFFFFFFFF
#define CSU_CSU_ROM_DIGEST_11_DIGEST_MASK	 0xFFFFFFFF 


/* SCRATCH_0 REGISTER */ 
#define CSU_SCRATCH_0	0xFFCA0100
#define CSU_SCRATCH_0_DEFVAL	0x0
#define CSU_SCRATCH_0_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_0_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_0_SCRATCH_WIDTH	32
#define CSU_SCRATCH_0_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_0_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_1 REGISTER */ 
#define CSU_SCRATCH_1	0xFFCA0104
#define CSU_SCRATCH_1_DEFVAL	0x0
#define CSU_SCRATCH_1_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_1_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_1_SCRATCH_WIDTH	32
#define CSU_SCRATCH_1_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_1_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_2 REGISTER */ 
#define CSU_SCRATCH_2	0xFFCA0108
#define CSU_SCRATCH_2_DEFVAL	0x0
#define CSU_SCRATCH_2_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_2_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_2_SCRATCH_WIDTH	32
#define CSU_SCRATCH_2_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_2_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_3 REGISTER */ 
#define CSU_SCRATCH_3	0xFFCA010C
#define CSU_SCRATCH_3_DEFVAL	0x0
#define CSU_SCRATCH_3_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_3_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_3_SCRATCH_WIDTH	32
#define CSU_SCRATCH_3_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_3_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_4 REGISTER */ 
#define CSU_SCRATCH_4	0xFFCA0110
#define CSU_SCRATCH_4_DEFVAL	0x0
#define CSU_SCRATCH_4_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_4_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_4_SCRATCH_WIDTH	32
#define CSU_SCRATCH_4_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_4_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_5 REGISTER */ 
#define CSU_SCRATCH_5	0xFFCA0114
#define CSU_SCRATCH_5_DEFVAL	0x0
#define CSU_SCRATCH_5_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_5_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_5_SCRATCH_WIDTH	32
#define CSU_SCRATCH_5_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_5_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_6 REGISTER */ 
#define CSU_SCRATCH_6	0xFFCA0118
#define CSU_SCRATCH_6_DEFVAL	0x0
#define CSU_SCRATCH_6_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_6_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_6_SCRATCH_WIDTH	32
#define CSU_SCRATCH_6_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_6_SCRATCH_MASK	 0xFFFFFFFF 


/* SCRATCH_7 REGISTER */ 
#define CSU_SCRATCH_7	0xFFCA011C
#define CSU_SCRATCH_7_DEFVAL	0x0
#define CSU_SCRATCH_7_CMP_MASK	0xFFFFFFFF
#define CSU_SCRATCH_7_SCRATCH_LSB_OFFSET	 0 
#define CSU_SCRATCH_7_SCRATCH_WIDTH	32
#define CSU_SCRATCH_7_SCRATCH_DEFVAL	0x0
#define CSU_SCRATCH_7_SCRATCH_MASK	 0xFFFFFFFF 


/* AES_STATUS REGISTER */ 
#define CSU_AES_STATUS	0xFFCA1000
#define CSU_AES_STATUS_DEFVAL	0xF00
#define CSU_AES_STATUS_CMP_MASK	0xFFF
#define CSU_AES_STATUS_OKR_ZEROED_LSB_OFFSET	 11 
#define CSU_AES_STATUS_OKR_ZEROED_WIDTH	1
#define CSU_AES_STATUS_OKR_ZEROED_DEFVAL	0x1
#define CSU_AES_STATUS_OKR_ZEROED_MASK	 0x800 

#define CSU_AES_STATUS_BOOT_ZEROED_LSB_OFFSET	 10 
#define CSU_AES_STATUS_BOOT_ZEROED_WIDTH	1
#define CSU_AES_STATUS_BOOT_ZEROED_DEFVAL	0x1
#define CSU_AES_STATUS_BOOT_ZEROED_MASK	 0x400 

#define CSU_AES_STATUS_KUP_ZEROED_LSB_OFFSET	 9 
#define CSU_AES_STATUS_KUP_ZEROED_WIDTH	1
#define CSU_AES_STATUS_KUP_ZEROED_DEFVAL	0x1
#define CSU_AES_STATUS_KUP_ZEROED_MASK	 0x200 

#define CSU_AES_STATUS_AES_KEY_ZEROED_LSB_OFFSET	 8 
#define CSU_AES_STATUS_AES_KEY_ZEROED_WIDTH	1
#define CSU_AES_STATUS_AES_KEY_ZEROED_DEFVAL	0x1
#define CSU_AES_STATUS_AES_KEY_ZEROED_MASK	 0x100 

#define CSU_AES_STATUS_BLACK_KEY_DONE_LSB_OFFSET	 5 
#define CSU_AES_STATUS_BLACK_KEY_DONE_WIDTH	1
#define CSU_AES_STATUS_BLACK_KEY_DONE_DEFVAL	0x0
#define CSU_AES_STATUS_BLACK_KEY_DONE_MASK	 0x20 

#define CSU_AES_STATUS_KEY_INIT_DONE_LSB_OFFSET	 4 
#define CSU_AES_STATUS_KEY_INIT_DONE_WIDTH	1
#define CSU_AES_STATUS_KEY_INIT_DONE_DEFVAL	0x0
#define CSU_AES_STATUS_KEY_INIT_DONE_MASK	 0x10 

#define CSU_AES_STATUS_GCM_TAG_PASS_LSB_OFFSET	 3 
#define CSU_AES_STATUS_GCM_TAG_PASS_WIDTH	1
#define CSU_AES_STATUS_GCM_TAG_PASS_DEFVAL	0x0
#define CSU_AES_STATUS_GCM_TAG_PASS_MASK	 0x8 

#define CSU_AES_STATUS_DONE_LSB_OFFSET	 2 
#define CSU_AES_STATUS_DONE_WIDTH	1
#define CSU_AES_STATUS_DONE_DEFVAL	0x0
#define CSU_AES_STATUS_DONE_MASK	 0x4 

#define CSU_AES_STATUS_READY_LSB_OFFSET	 1 
#define CSU_AES_STATUS_READY_WIDTH	1
#define CSU_AES_STATUS_READY_DEFVAL	0x0
#define CSU_AES_STATUS_READY_MASK	 0x2 

#define CSU_AES_STATUS_BUSY_LSB_OFFSET	 0 
#define CSU_AES_STATUS_BUSY_WIDTH	1
#define CSU_AES_STATUS_BUSY_DEFVAL	0x0
#define CSU_AES_STATUS_BUSY_MASK	 0x1 


/* AES_KEY_SRC REGISTER */ 
#define CSU_AES_KEY_SRC	0xFFCA1004
#define CSU_AES_KEY_SRC_DEFVAL	0x0
#define CSU_AES_KEY_SRC_CMP_MASK	0xF
#define CSU_AES_KEY_SRC_KEY_SRC_LSB_OFFSET	 0 
#define CSU_AES_KEY_SRC_KEY_SRC_WIDTH	4
#define CSU_AES_KEY_SRC_KEY_SRC_DEFVAL	0x0
#define CSU_AES_KEY_SRC_KEY_SRC_MASK	 0xF 


/* AES_KEY_LOAD REGISTER */ 
#define CSU_AES_KEY_LOAD	0xFFCA1008
#define CSU_AES_KEY_LOAD_DEFVAL	0x0
#define CSU_AES_KEY_LOAD_CMP_MASK	0x1
#define CSU_AES_KEY_LOAD_KEY_LOAD_LSB_OFFSET	 0 
#define CSU_AES_KEY_LOAD_KEY_LOAD_WIDTH	1
#define CSU_AES_KEY_LOAD_KEY_LOAD_DEFVAL	0x0
#define CSU_AES_KEY_LOAD_KEY_LOAD_MASK	 0x1 


/* AES_START_MSG REGISTER */ 
#define CSU_AES_START_MSG	0xFFCA100C
#define CSU_AES_START_MSG_DEFVAL	0x0
#define CSU_AES_START_MSG_CMP_MASK	0x1
#define CSU_AES_START_MSG_START_MSG_LSB_OFFSET	 0 
#define CSU_AES_START_MSG_START_MSG_WIDTH	1
#define CSU_AES_START_MSG_START_MSG_DEFVAL	0x0
#define CSU_AES_START_MSG_START_MSG_MASK	 0x1 


/* AES_RESET REGISTER */ 
#define CSU_AES_RESET	0xFFCA1010
#define CSU_AES_RESET_DEFVAL	0x0
#define CSU_AES_RESET_CMP_MASK	0x1
#define CSU_AES_RESET_RESET_LSB_OFFSET	 0 
#define CSU_AES_RESET_RESET_WIDTH	1
#define CSU_AES_RESET_RESET_DEFVAL	0x0
#define CSU_AES_RESET_RESET_MASK	 0x1 


/* AES_KEY_CLEAR REGISTER */ 
#define CSU_AES_KEY_CLEAR	0xFFCA1014
#define CSU_AES_KEY_CLEAR_DEFVAL	0x0
#define CSU_AES_KEY_CLEAR_CMP_MASK	0xF
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_LSB_OFFSET	 3 
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_WIDTH	1
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_DEFVAL	0x0
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_MASK	 0x8 

#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_LSB_OFFSET	 2 
#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_WIDTH	1
#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_DEFVAL	0x0
#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_MASK	 0x4 

#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_LSB_OFFSET	 1 
#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_WIDTH	1
#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_DEFVAL	0x0
#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_MASK	 0x2 

#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_LSB_OFFSET	 0 
#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_WIDTH	1
#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_DEFVAL	0x0
#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_MASK	 0x1 


/* AES_CFG REGISTER */ 
#define CSU_AES_CFG	0xFFCA1018
#define CSU_AES_CFG_DEFVAL	0x0
#define CSU_AES_CFG_CMP_MASK	0x1
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_LSB_OFFSET	 0 
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_WIDTH	1
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_DEFVAL	0x0
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_MASK	 0x1 


/* AES_KUP_WR REGISTER */ 
#define CSU_AES_KUP_WR	0xFFCA101C
#define CSU_AES_KUP_WR_DEFVAL	0x0
#define CSU_AES_KUP_WR_CMP_MASK	0x3
#define CSU_AES_KUP_WR_IV_WRITE_LSB_OFFSET	 1 
#define CSU_AES_KUP_WR_IV_WRITE_WIDTH	1
#define CSU_AES_KUP_WR_IV_WRITE_DEFVAL	0x0
#define CSU_AES_KUP_WR_IV_WRITE_MASK	 0x2 

#define CSU_AES_KUP_WR_KUP_WRITE_LSB_OFFSET	 0 
#define CSU_AES_KUP_WR_KUP_WRITE_WIDTH	1
#define CSU_AES_KUP_WR_KUP_WRITE_DEFVAL	0x0
#define CSU_AES_KUP_WR_KUP_WRITE_MASK	 0x1 


/* AES_KUP_0 REGISTER */ 
#define CSU_AES_KUP_0	0xFFCA1020
#define CSU_AES_KUP_0_DEFVAL	0x0
#define CSU_AES_KUP_0_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_0_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_0_AES_KEY_WIDTH	32
#define CSU_AES_KUP_0_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_0_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_1 REGISTER */ 
#define CSU_AES_KUP_1	0xFFCA1024
#define CSU_AES_KUP_1_DEFVAL	0x0
#define CSU_AES_KUP_1_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_1_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_1_AES_KEY_WIDTH	32
#define CSU_AES_KUP_1_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_1_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_2 REGISTER */ 
#define CSU_AES_KUP_2	0xFFCA1028
#define CSU_AES_KUP_2_DEFVAL	0x0
#define CSU_AES_KUP_2_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_2_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_2_AES_KEY_WIDTH	32
#define CSU_AES_KUP_2_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_2_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_3 REGISTER */ 
#define CSU_AES_KUP_3	0xFFCA102C
#define CSU_AES_KUP_3_DEFVAL	0x0
#define CSU_AES_KUP_3_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_3_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_3_AES_KEY_WIDTH	32
#define CSU_AES_KUP_3_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_3_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_4 REGISTER */ 
#define CSU_AES_KUP_4	0xFFCA1030
#define CSU_AES_KUP_4_DEFVAL	0x0
#define CSU_AES_KUP_4_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_4_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_4_AES_KEY_WIDTH	32
#define CSU_AES_KUP_4_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_4_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_5 REGISTER */ 
#define CSU_AES_KUP_5	0xFFCA1034
#define CSU_AES_KUP_5_DEFVAL	0x0
#define CSU_AES_KUP_5_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_5_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_5_AES_KEY_WIDTH	32
#define CSU_AES_KUP_5_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_5_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_6 REGISTER */ 
#define CSU_AES_KUP_6	0xFFCA1038
#define CSU_AES_KUP_6_DEFVAL	0x0
#define CSU_AES_KUP_6_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_6_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_6_AES_KEY_WIDTH	32
#define CSU_AES_KUP_6_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_6_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_KUP_7 REGISTER */ 
#define CSU_AES_KUP_7	0xFFCA103C
#define CSU_AES_KUP_7_DEFVAL	0x0
#define CSU_AES_KUP_7_CMP_MASK	0xFFFFFFFF
#define CSU_AES_KUP_7_AES_KEY_LSB_OFFSET	 0 
#define CSU_AES_KUP_7_AES_KEY_WIDTH	32
#define CSU_AES_KUP_7_AES_KEY_DEFVAL	0x0
#define CSU_AES_KUP_7_AES_KEY_MASK	 0xFFFFFFFF 


/* AES_IV_0 REGISTER */ 
#define CSU_AES_IV_0	0xFFCA1040
#define CSU_AES_IV_0_DEFVAL	0x0
#define CSU_AES_IV_0_CMP_MASK	0xFFFFFFFF
#define CSU_AES_IV_0_AES_IV_LSB_OFFSET	 0 
#define CSU_AES_IV_0_AES_IV_WIDTH	32
#define CSU_AES_IV_0_AES_IV_DEFVAL	0x0
#define CSU_AES_IV_0_AES_IV_MASK	 0xFFFFFFFF 


/* AES_IV_1 REGISTER */ 
#define CSU_AES_IV_1	0xFFCA1044
#define CSU_AES_IV_1_DEFVAL	0x0
#define CSU_AES_IV_1_CMP_MASK	0xFFFFFFFF
#define CSU_AES_IV_1_AES_IV_LSB_OFFSET	 0 
#define CSU_AES_IV_1_AES_IV_WIDTH	32
#define CSU_AES_IV_1_AES_IV_DEFVAL	0x0
#define CSU_AES_IV_1_AES_IV_MASK	 0xFFFFFFFF 


/* AES_IV_2 REGISTER */ 
#define CSU_AES_IV_2	0xFFCA1048
#define CSU_AES_IV_2_DEFVAL	0x0
#define CSU_AES_IV_2_CMP_MASK	0xFFFFFFFF
#define CSU_AES_IV_2_AES_IV_LSB_OFFSET	 0 
#define CSU_AES_IV_2_AES_IV_WIDTH	32
#define CSU_AES_IV_2_AES_IV_DEFVAL	0x0
#define CSU_AES_IV_2_AES_IV_MASK	 0xFFFFFFFF 


/* AES_IV_3 REGISTER */ 
#define CSU_AES_IV_3	0xFFCA104C
#define CSU_AES_IV_3_DEFVAL	0x0
#define CSU_AES_IV_3_CMP_MASK	0xFFFFFFFF
#define CSU_AES_IV_3_AES_IV_DLC_LSB_OFFSET	 0 
#define CSU_AES_IV_3_AES_IV_DLC_WIDTH	32
#define CSU_AES_IV_3_AES_IV_DLC_DEFVAL	0x0
#define CSU_AES_IV_3_AES_IV_DLC_MASK	 0xFFFFFFFF 


/* SHA_START REGISTER */ 
#define CSU_SHA_START	0xFFCA2000
#define CSU_SHA_START_DEFVAL	0x0
#define CSU_SHA_START_CMP_MASK	0x1
#define CSU_SHA_START_START_MSG_LSB_OFFSET	 0 
#define CSU_SHA_START_START_MSG_WIDTH	1
#define CSU_SHA_START_START_MSG_DEFVAL	0x0
#define CSU_SHA_START_START_MSG_MASK	 0x1 


/* SHA_RESET REGISTER */ 
#define CSU_SHA_RESET	0xFFCA2004
#define CSU_SHA_RESET_DEFVAL	0x0
#define CSU_SHA_RESET_CMP_MASK	0x1
#define CSU_SHA_RESET_RESET_LSB_OFFSET	 0 
#define CSU_SHA_RESET_RESET_WIDTH	1
#define CSU_SHA_RESET_RESET_DEFVAL	0x0
#define CSU_SHA_RESET_RESET_MASK	 0x1 


/* SHA_DONE REGISTER */ 
#define CSU_SHA_DONE	0xFFCA2008
#define CSU_SHA_DONE_DEFVAL	0x0
#define CSU_SHA_DONE_CMP_MASK	0x1
#define CSU_SHA_DONE_SHA_DONE_LSB_OFFSET	 0 
#define CSU_SHA_DONE_SHA_DONE_WIDTH	1
#define CSU_SHA_DONE_SHA_DONE_DEFVAL	0x0
#define CSU_SHA_DONE_SHA_DONE_MASK	 0x1 


/* SHA_DIGEST_0 REGISTER */ 
#define CSU_SHA_DIGEST_0	0xFFCA2010
#define CSU_SHA_DIGEST_0_DEFVAL	0x0
#define CSU_SHA_DIGEST_0_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_0_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_0_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_0_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_0_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_1 REGISTER */ 
#define CSU_SHA_DIGEST_1	0xFFCA2014
#define CSU_SHA_DIGEST_1_DEFVAL	0x0
#define CSU_SHA_DIGEST_1_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_1_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_1_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_1_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_1_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_2 REGISTER */ 
#define CSU_SHA_DIGEST_2	0xFFCA2018
#define CSU_SHA_DIGEST_2_DEFVAL	0x0
#define CSU_SHA_DIGEST_2_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_2_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_2_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_2_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_2_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_3 REGISTER */ 
#define CSU_SHA_DIGEST_3	0xFFCA201C
#define CSU_SHA_DIGEST_3_DEFVAL	0x0
#define CSU_SHA_DIGEST_3_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_3_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_3_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_3_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_3_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_4 REGISTER */ 
#define CSU_SHA_DIGEST_4	0xFFCA2020
#define CSU_SHA_DIGEST_4_DEFVAL	0x0
#define CSU_SHA_DIGEST_4_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_4_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_4_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_4_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_4_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_5 REGISTER */ 
#define CSU_SHA_DIGEST_5	0xFFCA2024
#define CSU_SHA_DIGEST_5_DEFVAL	0x0
#define CSU_SHA_DIGEST_5_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_5_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_5_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_5_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_5_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_6 REGISTER */ 
#define CSU_SHA_DIGEST_6	0xFFCA2028
#define CSU_SHA_DIGEST_6_DEFVAL	0x0
#define CSU_SHA_DIGEST_6_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_6_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_6_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_6_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_6_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_7 REGISTER */ 
#define CSU_SHA_DIGEST_7	0xFFCA202C
#define CSU_SHA_DIGEST_7_DEFVAL	0x0
#define CSU_SHA_DIGEST_7_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_7_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_7_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_7_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_7_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_8 REGISTER */ 
#define CSU_SHA_DIGEST_8	0xFFCA2030
#define CSU_SHA_DIGEST_8_DEFVAL	0x0
#define CSU_SHA_DIGEST_8_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_8_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_8_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_8_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_8_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_9 REGISTER */ 
#define CSU_SHA_DIGEST_9	0xFFCA2034
#define CSU_SHA_DIGEST_9_DEFVAL	0x0
#define CSU_SHA_DIGEST_9_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_9_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_9_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_9_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_9_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_10 REGISTER */ 
#define CSU_SHA_DIGEST_10	0xFFCA2038
#define CSU_SHA_DIGEST_10_DEFVAL	0x0
#define CSU_SHA_DIGEST_10_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_10_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_10_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_10_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_10_DIGEST_MASK	 0xFFFFFFFF 


/* SHA_DIGEST_11 REGISTER */ 
#define CSU_SHA_DIGEST_11	0xFFCA203C
#define CSU_SHA_DIGEST_11_DEFVAL	0x0
#define CSU_SHA_DIGEST_11_CMP_MASK	0xFFFFFFFF
#define CSU_SHA_DIGEST_11_DIGEST_LSB_OFFSET	 0 
#define CSU_SHA_DIGEST_11_DIGEST_WIDTH	32
#define CSU_SHA_DIGEST_11_DIGEST_DEFVAL	0x0
#define CSU_SHA_DIGEST_11_DIGEST_MASK	 0xFFFFFFFF 


/* PCAP_PROG REGISTER */ 
#define CSU_PCAP_PROG	0xFFCA3000
#define CSU_PCAP_PROG_DEFVAL	0x0
#define CSU_PCAP_PROG_CMP_MASK	0x1
#define CSU_PCAP_PROG_PCFG_PROG_B_LSB_OFFSET	 0 
#define CSU_PCAP_PROG_PCFG_PROG_B_WIDTH	1
#define CSU_PCAP_PROG_PCFG_PROG_B_DEFVAL	0x0
#define CSU_PCAP_PROG_PCFG_PROG_B_MASK	 0x1 


/* PCAP_RDWR REGISTER */ 
#define CSU_PCAP_RDWR	0xFFCA3004
#define CSU_PCAP_RDWR_DEFVAL	0x0
#define CSU_PCAP_RDWR_CMP_MASK	0x1
#define CSU_PCAP_RDWR_PCAP_RDWR_B_LSB_OFFSET	 0 
#define CSU_PCAP_RDWR_PCAP_RDWR_B_WIDTH	1
#define CSU_PCAP_RDWR_PCAP_RDWR_B_DEFVAL	0x0
#define CSU_PCAP_RDWR_PCAP_RDWR_B_MASK	 0x1 


/* PCAP_CTRL REGISTER */ 
#define CSU_PCAP_CTRL	0xFFCA3008
#define CSU_PCAP_CTRL_DEFVAL	0x1
#define CSU_PCAP_CTRL_CMP_MASK	0xF
#define CSU_PCAP_CTRL_PCFG_GSR_LSB_OFFSET	 3 
#define CSU_PCAP_CTRL_PCFG_GSR_WIDTH	1
#define CSU_PCAP_CTRL_PCFG_GSR_DEFVAL	0x0
#define CSU_PCAP_CTRL_PCFG_GSR_MASK	 0x8 

#define CSU_PCAP_CTRL_PCFG_GTS_LSB_OFFSET	 2 
#define CSU_PCAP_CTRL_PCFG_GTS_WIDTH	1
#define CSU_PCAP_CTRL_PCFG_GTS_DEFVAL	0x0
#define CSU_PCAP_CTRL_PCFG_GTS_MASK	 0x4 

#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_LSB_OFFSET	 1 
#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_WIDTH	1
#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_DEFVAL	0x0
#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_MASK	 0x2 

#define CSU_PCAP_CTRL_PCAP_PR_LSB_OFFSET	 0 
#define CSU_PCAP_CTRL_PCAP_PR_WIDTH	1
#define CSU_PCAP_CTRL_PCAP_PR_DEFVAL	0x1
#define CSU_PCAP_CTRL_PCAP_PR_MASK	 0x1 


/* PCAP_RESET REGISTER */ 
#define CSU_PCAP_RESET	0xFFCA300C
#define CSU_PCAP_RESET_DEFVAL	0x0
#define CSU_PCAP_RESET_CMP_MASK	0x1
#define CSU_PCAP_RESET_RESET_LSB_OFFSET	 0 
#define CSU_PCAP_RESET_RESET_WIDTH	1
#define CSU_PCAP_RESET_RESET_DEFVAL	0x0
#define CSU_PCAP_RESET_RESET_MASK	 0x1 


/* PCAP_STATUS REGISTER */ 
#define CSU_PCAP_STATUS	0xFFCA3010
#define CSU_PCAP_STATUS_DEFVAL	0x3
#define CSU_PCAP_STATUS_CMP_MASK	0xFFFFFFFF
#define CSU_PCAP_STATUS_PCFG_FUSE_PL_DIS_LSB_OFFSET	 31 
#define CSU_PCAP_STATUS_PCFG_FUSE_PL_DIS_WIDTH	1
#define CSU_PCAP_STATUS_PCFG_FUSE_PL_DIS_DEFVAL	0x0
#define CSU_PCAP_STATUS_PCFG_FUSE_PL_DIS_MASK	 0x80000000 

#define CSU_PCAP_STATUS_PCFG_PL_CFG_USED_LSB_OFFSET	 30 
#define CSU_PCAP_STATUS_PCFG_PL_CFG_USED_WIDTH	1
#define CSU_PCAP_STATUS_PCFG_PL_CFG_USED_DEFVAL	0x0
#define CSU_PCAP_STATUS_PCFG_PL_CFG_USED_MASK	 0x40000000 

#define CSU_PCAP_STATUS_PCFG_IS_ZYNQ_LSB_OFFSET	 29 
#define CSU_PCAP_STATUS_PCFG_IS_ZYNQ_WIDTH	1
#define CSU_PCAP_STATUS_PCFG_IS_ZYNQ_DEFVAL	0x0
#define CSU_PCAP_STATUS_PCFG_IS_ZYNQ_MASK	 0x20000000 

#define CSU_PCAP_STATUS_PCFG_GWE_LSB_OFFSET	 13 
#define CSU_PCAP_STATUS_PCFG_GWE_WIDTH	1
#define CSU_PCAP_STATUS_PCFG_GWE_DEFVAL	0x0
#define CSU_PCAP_STATUS_PCFG_GWE_MASK	 0x2000 

#define CSU_PCAP_STATUS_PCFG_MCAP_MODE_LSB_OFFSET	 12 
#define CSU_PCAP_STATUS_PCFG_MCAP_MODE_WIDTH	1
#define CSU_PCAP_STATUS_PCFG_MCAP_MODE_DEFVAL	0x0
#define CSU_PCAP_STATUS_PCFG_MCAP_MODE_MASK	 0x1000 

#define CSU_PCAP_STATUS_PL_GTS_USR_B_LSB_OFFSET	 11 
#define CSU_PCAP_STATUS_PL_GTS_USR_B_WIDTH	1
#define CSU_PCAP_STATUS_PL_GTS_USR_B_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_GTS_USR_B_MASK	 0x800 

#define CSU_PCAP_STATUS_PL_GTS_CFG_B_LSB_OFFSET	 10 
#define CSU_PCAP_STATUS_PL_GTS_CFG_B_WIDTH	1
#define CSU_PCAP_STATUS_PL_GTS_CFG_B_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_GTS_CFG_B_MASK	 0x400 

#define CSU_PCAP_STATUS_PL_GPWRDWN_B_LSB_OFFSET	 9 
#define CSU_PCAP_STATUS_PL_GPWRDWN_B_WIDTH	1
#define CSU_PCAP_STATUS_PL_GPWRDWN_B_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_GPWRDWN_B_MASK	 0x200 

#define CSU_PCAP_STATUS_PL_GHIGH_B_LSB_OFFSET	 8 
#define CSU_PCAP_STATUS_PL_GHIGH_B_WIDTH	1
#define CSU_PCAP_STATUS_PL_GHIGH_B_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_GHIGH_B_MASK	 0x100 

#define CSU_PCAP_STATUS_PL_FST_CFG_LSB_OFFSET	 7 
#define CSU_PCAP_STATUS_PL_FST_CFG_WIDTH	1
#define CSU_PCAP_STATUS_PL_FST_CFG_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_FST_CFG_MASK	 0x80 

#define CSU_PCAP_STATUS_PL_CFG_RESET_B_LSB_OFFSET	 6 
#define CSU_PCAP_STATUS_PL_CFG_RESET_B_WIDTH	1
#define CSU_PCAP_STATUS_PL_CFG_RESET_B_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_CFG_RESET_B_MASK	 0x40 

#define CSU_PCAP_STATUS_PL_SEU_ERROR_LSB_OFFSET	 5 
#define CSU_PCAP_STATUS_PL_SEU_ERROR_WIDTH	1
#define CSU_PCAP_STATUS_PL_SEU_ERROR_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_SEU_ERROR_MASK	 0x20 

#define CSU_PCAP_STATUS_PL_EOS_LSB_OFFSET	 4 
#define CSU_PCAP_STATUS_PL_EOS_WIDTH	1
#define CSU_PCAP_STATUS_PL_EOS_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_EOS_MASK	 0x10 

#define CSU_PCAP_STATUS_PL_DONE_LSB_OFFSET	 3 
#define CSU_PCAP_STATUS_PL_DONE_WIDTH	1
#define CSU_PCAP_STATUS_PL_DONE_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_DONE_MASK	 0x8 

#define CSU_PCAP_STATUS_PL_INIT_LSB_OFFSET	 2 
#define CSU_PCAP_STATUS_PL_INIT_WIDTH	1
#define CSU_PCAP_STATUS_PL_INIT_DEFVAL	0x0
#define CSU_PCAP_STATUS_PL_INIT_MASK	 0x4 

#define CSU_PCAP_STATUS_PCAP_RD_IDLE_LSB_OFFSET	 1 
#define CSU_PCAP_STATUS_PCAP_RD_IDLE_WIDTH	1
#define CSU_PCAP_STATUS_PCAP_RD_IDLE_DEFVAL	0x1
#define CSU_PCAP_STATUS_PCAP_RD_IDLE_MASK	 0x2 

#define CSU_PCAP_STATUS_PCAP_WR_IDLE_LSB_OFFSET	 0 
#define CSU_PCAP_STATUS_PCAP_WR_IDLE_WIDTH	1
#define CSU_PCAP_STATUS_PCAP_WR_IDLE_DEFVAL	0x1
#define CSU_PCAP_STATUS_PCAP_WR_IDLE_MASK	 0x1 


/* PUF_CMD REGISTER */ 
#define CSU_PUF_CMD	0xFFCA4000
#define CSU_PUF_CMD_DEFVAL	0x0
#define CSU_PUF_CMD_CMP_MASK	0xF
#define CSU_PUF_CMD_CMD_LSB_OFFSET	 0 
#define CSU_PUF_CMD_CMD_WIDTH	4
#define CSU_PUF_CMD_CMD_DEFVAL	0x0
#define CSU_PUF_CMD_CMD_MASK	 0xF 


/* PUF_CFG0 REGISTER */ 
#define CSU_PUF_CFG0	0xFFCA4004
#define CSU_PUF_CFG0_DEFVAL	0x2
#define CSU_PUF_CFG0_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_CFG0_CFG0_LSB_OFFSET	 0 
#define CSU_PUF_CFG0_CFG0_WIDTH	32
#define CSU_PUF_CFG0_CFG0_DEFVAL	0x2
#define CSU_PUF_CFG0_CFG0_MASK	 0xFFFFFFFF 


/* PUF_CFG1 REGISTER */ 
#define CSU_PUF_CFG1	0xFFCA4008
#define CSU_PUF_CFG1_DEFVAL	0x80080
#define CSU_PUF_CFG1_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_CFG1_CFG1_LSB_OFFSET	 0 
#define CSU_PUF_CFG1_CFG1_WIDTH	32
#define CSU_PUF_CFG1_CFG1_DEFVAL	0x80080
#define CSU_PUF_CFG1_CFG1_MASK	 0xFFFFFFFF 


/* PUF_SHUT REGISTER */ 
#define CSU_PUF_SHUT	0xFFCA400C
#define CSU_PUF_SHUT_DEFVAL	0x1000020
#define CSU_PUF_SHUT_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_SHUT_SOSET_LSB_OFFSET	 24 
#define CSU_PUF_SHUT_SOSET_WIDTH	8
#define CSU_PUF_SHUT_SOSET_DEFVAL	0x1
#define CSU_PUF_SHUT_SOSET_MASK	 0xFF000000 

#define CSU_PUF_SHUT_SOPEN_LSB_OFFSET	 0 
#define CSU_PUF_SHUT_SOPEN_WIDTH	24
#define CSU_PUF_SHUT_SOPEN_DEFVAL	0x20
#define CSU_PUF_SHUT_SOPEN_MASK	 0xFFFFFF 


/* PUF_STATUS REGISTER */ 
#define CSU_PUF_STATUS	0xFFCA4010
#define CSU_PUF_STATUS_DEFVAL	0x0
#define CSU_PUF_STATUS_CMP_MASK	0x3FFFFFFF
#define CSU_PUF_STATUS_OVERFLOW_LSB_OFFSET	 28 
#define CSU_PUF_STATUS_OVERFLOW_WIDTH	2
#define CSU_PUF_STATUS_OVERFLOW_DEFVAL	0x0
#define CSU_PUF_STATUS_OVERFLOW_MASK	 0x30000000 

#define CSU_PUF_STATUS_AUX_LSB_OFFSET	 4 
#define CSU_PUF_STATUS_AUX_WIDTH	24
#define CSU_PUF_STATUS_AUX_DEFVAL	0x0
#define CSU_PUF_STATUS_AUX_MASK	 0xFFFFFF0 

#define CSU_PUF_STATUS_KEY_RDY_LSB_OFFSET	 3 
#define CSU_PUF_STATUS_KEY_RDY_WIDTH	1
#define CSU_PUF_STATUS_KEY_RDY_DEFVAL	0x0
#define CSU_PUF_STATUS_KEY_RDY_MASK	 0x8 

#define CSU_PUF_STATUS_KEY_ZERO_LSB_OFFSET	 1 
#define CSU_PUF_STATUS_KEY_ZERO_WIDTH	1
#define CSU_PUF_STATUS_KEY_ZERO_DEFVAL	0x0
#define CSU_PUF_STATUS_KEY_ZERO_MASK	 0x2 

#define CSU_PUF_STATUS_SYN_WRD_RDY_LSB_OFFSET	 0 
#define CSU_PUF_STATUS_SYN_WRD_RDY_WIDTH	1
#define CSU_PUF_STATUS_SYN_WRD_RDY_DEFVAL	0x0
#define CSU_PUF_STATUS_SYN_WRD_RDY_MASK	 0x1 


/* PUF_DBG REGISTER */ 
#define CSU_PUF_DBG	0xFFCA4014
#define CSU_PUF_DBG_DEFVAL	0x0
#define CSU_PUF_DBG_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_DBG_DBG_LSB_OFFSET	 0 
#define CSU_PUF_DBG_DBG_WIDTH	32
#define CSU_PUF_DBG_DBG_DEFVAL	0x0
#define CSU_PUF_DBG_DBG_MASK	 0xFFFFFFFF 


/* PUF_WORD REGISTER */ 
#define CSU_PUF_WORD	0xFFCA4018
#define CSU_PUF_WORD_DEFVAL	0x0
#define CSU_PUF_WORD_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_WORD_WORD_LSB_OFFSET	 0 
#define CSU_PUF_WORD_WORD_WIDTH	32
#define CSU_PUF_WORD_WORD_DEFVAL	0x0
#define CSU_PUF_WORD_WORD_MASK	 0xFFFFFFFF 


/* PUF_TM_STATUS REGISTER */ 
#define CSU_PUF_TM_STATUS	0xFFCA4804
#define CSU_PUF_TM_STATUS_DEFVAL	0x0
#define CSU_PUF_TM_STATUS_CMP_MASK	0x1
#define CSU_PUF_TM_STATUS_DN_LSB_OFFSET	 0 
#define CSU_PUF_TM_STATUS_DN_WIDTH	1
#define CSU_PUF_TM_STATUS_DN_DEFVAL	0x0
#define CSU_PUF_TM_STATUS_DN_MASK	 0x1 


/* PUF_TM_UL REGISTER */ 
#define CSU_PUF_TM_UL	0xFFCA4808
#define CSU_PUF_TM_UL_DEFVAL	0x0
#define CSU_PUF_TM_UL_CMP_MASK	0x3FFFF
#define CSU_PUF_TM_UL_UL_LSB_OFFSET	 0 
#define CSU_PUF_TM_UL_UL_WIDTH	18
#define CSU_PUF_TM_UL_UL_DEFVAL	0x0
#define CSU_PUF_TM_UL_UL_MASK	 0x3FFFF 


/* PUF_TM_LL REGISTER */ 
#define CSU_PUF_TM_LL	0xFFCA480C
#define CSU_PUF_TM_LL_DEFVAL	0x0
#define CSU_PUF_TM_LL_CMP_MASK	0x3FFFF
#define CSU_PUF_TM_LL_LL_LSB_OFFSET	 0 
#define CSU_PUF_TM_LL_LL_WIDTH	18
#define CSU_PUF_TM_LL_LL_DEFVAL	0x0
#define CSU_PUF_TM_LL_LL_MASK	 0x3FFFF 


/* PUF_TM_SW REGISTER */ 
#define CSU_PUF_TM_SW	0xFFCA4810
#define CSU_PUF_TM_SW_DEFVAL	0x1000020
#define CSU_PUF_TM_SW_CMP_MASK	0xFFFFFFFF
#define CSU_PUF_TM_SW_OFF_LSB_OFFSET	 24 
#define CSU_PUF_TM_SW_OFF_WIDTH	8
#define CSU_PUF_TM_SW_OFF_DEFVAL	0x1
#define CSU_PUF_TM_SW_OFF_MASK	 0xFF000000 

#define CSU_PUF_TM_SW_SW_LSB_OFFSET	 0 
#define CSU_PUF_TM_SW_SW_WIDTH	24
#define CSU_PUF_TM_SW_SW_DEFVAL	0x20
#define CSU_PUF_TM_SW_SW_MASK	 0xFFFFFF 


/* PUF_TM_TR REGISTER */ 
#define CSU_PUF_TM_TR	0xFFCA4814
#define CSU_PUF_TM_TR_DEFVAL	0x0
#define CSU_PUF_TM_TR_CMP_MASK	0x3FFFFFF
#define CSU_PUF_TM_TR_US_LSB_OFFSET	 24 
#define CSU_PUF_TM_TR_US_WIDTH	2
#define CSU_PUF_TM_TR_US_DEFVAL	0x0
#define CSU_PUF_TM_TR_US_MASK	 0x3000000 

#define CSU_PUF_TM_TR_ER_LSB_OFFSET	 16 
#define CSU_PUF_TM_TR_ER_WIDTH	8
#define CSU_PUF_TM_TR_ER_DEFVAL	0x0
#define CSU_PUF_TM_TR_ER_MASK	 0xFF0000 

#define CSU_PUF_TM_TR_FRR_LSB_OFFSET	 0 
#define CSU_PUF_TM_TR_FRR_WIDTH	1
#define CSU_PUF_TM_TR_FRR_DEFVAL	0x0
#define CSU_PUF_TM_TR_FRR_MASK	 0x1 


/* TAMPER_STATUS REGISTER */ 
#define CSU_TAMPER_STATUS	0xFFCA5000
#define CSU_TAMPER_STATUS_DEFVAL	0x0
#define CSU_TAMPER_STATUS_CMP_MASK	0x3FFF
#define CSU_TAMPER_STATUS_TAMPER_13_LSB_OFFSET	 13 
#define CSU_TAMPER_STATUS_TAMPER_13_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_13_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_13_MASK	 0x2000 

#define CSU_TAMPER_STATUS_TAMPER_12_LSB_OFFSET	 12 
#define CSU_TAMPER_STATUS_TAMPER_12_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_12_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_12_MASK	 0x1000 

#define CSU_TAMPER_STATUS_TAMPER_11_LSB_OFFSET	 11 
#define CSU_TAMPER_STATUS_TAMPER_11_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_11_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_11_MASK	 0x800 

#define CSU_TAMPER_STATUS_TAMPER_10_LSB_OFFSET	 10 
#define CSU_TAMPER_STATUS_TAMPER_10_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_10_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_10_MASK	 0x400 

#define CSU_TAMPER_STATUS_TAMPER_9_LSB_OFFSET	 9 
#define CSU_TAMPER_STATUS_TAMPER_9_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_9_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_9_MASK	 0x200 

#define CSU_TAMPER_STATUS_TAMPER_8_LSB_OFFSET	 8 
#define CSU_TAMPER_STATUS_TAMPER_8_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_8_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_8_MASK	 0x100 

#define CSU_TAMPER_STATUS_TAMPER_7_LSB_OFFSET	 7 
#define CSU_TAMPER_STATUS_TAMPER_7_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_7_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_7_MASK	 0x80 

#define CSU_TAMPER_STATUS_TAMPER_6_LSB_OFFSET	 6 
#define CSU_TAMPER_STATUS_TAMPER_6_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_6_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_6_MASK	 0x40 

#define CSU_TAMPER_STATUS_TAMPER_5_LSB_OFFSET	 5 
#define CSU_TAMPER_STATUS_TAMPER_5_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_5_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_5_MASK	 0x20 

#define CSU_TAMPER_STATUS_TAMPER_4_LSB_OFFSET	 4 
#define CSU_TAMPER_STATUS_TAMPER_4_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_4_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_4_MASK	 0x10 

#define CSU_TAMPER_STATUS_TAMPER_3_LSB_OFFSET	 3 
#define CSU_TAMPER_STATUS_TAMPER_3_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_3_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_3_MASK	 0x8 

#define CSU_TAMPER_STATUS_TAMPER_2_LSB_OFFSET	 2 
#define CSU_TAMPER_STATUS_TAMPER_2_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_2_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_2_MASK	 0x4 

#define CSU_TAMPER_STATUS_TAMPER_1_LSB_OFFSET	 1 
#define CSU_TAMPER_STATUS_TAMPER_1_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_1_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_1_MASK	 0x2 

#define CSU_TAMPER_STATUS_TAMPER_0_LSB_OFFSET	 0 
#define CSU_TAMPER_STATUS_TAMPER_0_WIDTH	1
#define CSU_TAMPER_STATUS_TAMPER_0_DEFVAL	0x0
#define CSU_TAMPER_STATUS_TAMPER_0_MASK	 0x1 


/* CSU_TAMPER_0 REGISTER */ 
#define CSU_CSU_TAMPER_0	0xFFCA5004
#define CSU_CSU_TAMPER_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_CMP_MASK	0x2F
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_LSB_OFFSET	 5 
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_MASK	 0x20 

#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_0_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_0_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_0_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_1 REGISTER */ 
#define CSU_CSU_TAMPER_1	0xFFCA5008
#define CSU_CSU_TAMPER_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_1_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_1_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_1_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_2 REGISTER */ 
#define CSU_CSU_TAMPER_2	0xFFCA500C
#define CSU_CSU_TAMPER_2_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_2_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_2_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_2_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_3 REGISTER */ 
#define CSU_CSU_TAMPER_3	0xFFCA5010
#define CSU_CSU_TAMPER_3_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_3_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_3_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_3_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_4 REGISTER */ 
#define CSU_CSU_TAMPER_4	0xFFCA5014
#define CSU_CSU_TAMPER_4_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_4_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_4_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_4_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_5 REGISTER */ 
#define CSU_CSU_TAMPER_5	0xFFCA5018
#define CSU_CSU_TAMPER_5_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_5_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_5_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_5_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_6 REGISTER */ 
#define CSU_CSU_TAMPER_6	0xFFCA501C
#define CSU_CSU_TAMPER_6_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_6_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_6_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_6_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_7 REGISTER */ 
#define CSU_CSU_TAMPER_7	0xFFCA5020
#define CSU_CSU_TAMPER_7_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_7_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_7_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_7_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_8 REGISTER */ 
#define CSU_CSU_TAMPER_8	0xFFCA5024
#define CSU_CSU_TAMPER_8_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_8_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_8_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_8_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_9 REGISTER */ 
#define CSU_CSU_TAMPER_9	0xFFCA5028
#define CSU_CSU_TAMPER_9_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_9_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_9_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_9_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_10 REGISTER */ 
#define CSU_CSU_TAMPER_10	0xFFCA502C
#define CSU_CSU_TAMPER_10_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_10_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_10_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_10_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_11 REGISTER */ 
#define CSU_CSU_TAMPER_11	0xFFCA5030
#define CSU_CSU_TAMPER_11_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_11_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_11_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_11_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_12 REGISTER */ 
#define CSU_CSU_TAMPER_12	0xFFCA5034
#define CSU_CSU_TAMPER_12_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_12_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_12_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_12_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_13 REGISTER */ 
#define CSU_CSU_TAMPER_13	0xFFCA5038
#define CSU_CSU_TAMPER_13_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_13_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_13_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_13_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_MASK	 0x1 


/* CSU_TAMPER_14 REGISTER */ 
#define CSU_CSU_TAMPER_14	0xFFCA503C
#define CSU_CSU_TAMPER_14_DEFVAL	0xC
#define CSU_CSU_TAMPER_14_CMP_MASK	0x1F
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_LSB_OFFSET	 4 
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_WIDTH	1
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_DEFVAL	0x0
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_MASK	 0x10 

#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_LSB_OFFSET	 3 
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_WIDTH	1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_DEFVAL	0x1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_MASK	 0x8 

#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_LSB_OFFSET	 2 
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_WIDTH	1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_DEFVAL	0x1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_MASK	 0x4 

#define CSU_CSU_TAMPER_14_SYS_RESET_LSB_OFFSET	 1 
#define CSU_CSU_TAMPER_14_SYS_RESET_WIDTH	1
#define CSU_CSU_TAMPER_14_SYS_RESET_DEFVAL	0x0
#define CSU_CSU_TAMPER_14_SYS_RESET_MASK	 0x2 

#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_LSB_OFFSET	 0 
#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_WIDTH	1
#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_DEFVAL	0x0
#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_MASK	 0x1 


/* CSU_RAM_CFG REGISTER */ 
#define CSU_CSU_RAM_CFG	0xFFCAF000
#define CSU_CSU_RAM_CFG_DEFVAL	0x2DDB2CB
#define CSU_CSU_RAM_CFG_CMP_MASK	0x3FFFFFF
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAS_LSB_OFFSET	 25 
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAS_WIDTH	1
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAS_DEFVAL	0x1
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAS_MASK	 0x2000000 

#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_LSB_OFFSET	 22 
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_WIDTH	3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_MASK	 0x1C00000 

#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_LSB_OFFSET	 19 
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_WIDTH	3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_MASK	 0x380000 

#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAS_LSB_OFFSET	 18 
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAS_WIDTH	1
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAS_DEFVAL	0x1
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAS_MASK	 0x40000 

#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_LSB_OFFSET	 15 
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_WIDTH	3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_MASK	 0x38000 

#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_LSB_OFFSET	 12 
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_WIDTH	3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_MASK	 0x7000 

#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_LSB_OFFSET	 11 
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_WIDTH	1
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_DEFVAL	0x0
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_MASK	 0x800 

#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_LSB_OFFSET	 9 
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_WIDTH	2
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_DEFVAL	0x1
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_MASK	 0x600 

#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_LSB_OFFSET	 6 
#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_WIDTH	3
#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_MASK	 0x1C0 

#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_LSB_OFFSET	 5 
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_WIDTH	1
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_DEFVAL	0x0
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_MASK	 0x20 

#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_LSB_OFFSET	 3 
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_WIDTH	2
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_DEFVAL	0x1
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_MASK	 0x18 

#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_LSB_OFFSET	 0 
#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_WIDTH	3
#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_DEFVAL	0x3
#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_MASK	 0x7 


/* CSU_ROM_CFG REGISTER */ 
#define CSU_CSU_ROM_CFG	0xFFCAF004
#define CSU_CSU_ROM_CFG_DEFVAL	0x3
#define CSU_CSU_ROM_CFG_CMP_MASK	0xF
#define CSU_CSU_ROM_CFG_ROM_KEN_LSB_OFFSET	 3 
#define CSU_CSU_ROM_CFG_ROM_KEN_WIDTH	1
#define CSU_CSU_ROM_CFG_ROM_KEN_DEFVAL	0x0
#define CSU_CSU_ROM_CFG_ROM_KEN_MASK	 0x8 

#define CSU_CSU_ROM_CFG_ROM_EMA_LSB_OFFSET	 0 
#define CSU_CSU_ROM_CFG_ROM_EMA_WIDTH	3
#define CSU_CSU_ROM_CFG_ROM_EMA_DEFVAL	0x3
#define CSU_CSU_ROM_CFG_ROM_EMA_MASK	 0x7 


/* TEST_CSU_CTRL REGISTER */ 
#define CSU_TEST_CSU_CTRL	0xFFCAF008
#define CSU_TEST_CSU_CTRL_DEFVAL	0x0
#define CSU_TEST_CSU_CTRL_CMP_MASK	0xF
#define CSU_TEST_CSU_CTRL_SSSS_SYSOSC_SEL_LSB_OFFSET	 1 
#define CSU_TEST_CSU_CTRL_SSSS_SYSOSC_SEL_WIDTH	3
#define CSU_TEST_CSU_CTRL_SSSS_SYSOSC_SEL_DEFVAL	0x0
#define CSU_TEST_CSU_CTRL_SSSS_SYSOSC_SEL_MASK	 0xE 

#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_LSB_OFFSET	 0 
#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_WIDTH	1
#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_DEFVAL	0x0
#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_MASK	 0x1 


/* CSU_ECO_0 REGISTER */ 
#define CSU_CSU_ECO_0	0xFFCAFFF4
#define CSU_CSU_ECO_0_DEFVAL	0x0
#define CSU_CSU_ECO_0_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ECO_0_ECO_LSB_OFFSET	 0 
#define CSU_CSU_ECO_0_ECO_WIDTH	32
#define CSU_CSU_ECO_0_ECO_DEFVAL	0x0
#define CSU_CSU_ECO_0_ECO_MASK	 0xFFFFFFFF 


/* CSU_ECO_1 REGISTER */ 
#define CSU_CSU_ECO_1	0xFFCAFFF8
#define CSU_CSU_ECO_1_DEFVAL	0x0
#define CSU_CSU_ECO_1_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ECO_1_ECO_LSB_OFFSET	 0 
#define CSU_CSU_ECO_1_ECO_WIDTH	32
#define CSU_CSU_ECO_1_ECO_DEFVAL	0x0
#define CSU_CSU_ECO_1_ECO_MASK	 0xFFFFFFFF 


/* CSU_ECO_2 REGISTER */ 
#define CSU_CSU_ECO_2	0xFFCAFFFC
#define CSU_CSU_ECO_2_DEFVAL	0x0
#define CSU_CSU_ECO_2_CMP_MASK	0xFFFFFFFF
#define CSU_CSU_ECO_2_ECO_LSB_OFFSET	 0 
#define CSU_CSU_ECO_2_ECO_WIDTH	32
#define CSU_CSU_ECO_2_ECO_DEFVAL	0x0
#define CSU_CSU_ECO_2_ECO_MASK	 0xFFFFFFFF 

#endif
