# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# XDC: /home/ab/Documents/Projekty/2020-HyperK/iwcd-xu1-petalinux-rev0-2020-01/XU1_petalinux/src/MercuryXU1_NuPRISM.xdc

# IP: ip/c_shift_ram_0/c_shift_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# Block Designs: bd/MercuryXU1/MercuryXU1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1 || ORIG_REF_NAME==MercuryXU1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xbar_1/MercuryXU1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xbar_1 || ORIG_REF_NAME==MercuryXU1_xbar_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_ps8_0_axi_periph_0/MercuryXU1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_ps8_0_axi_periph_0 || ORIG_REF_NAME==MercuryXU1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlconcat_0_0/MercuryXU1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlconcat_0_0 || ORIG_REF_NAME==MercuryXU1_xlconcat_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/MercuryXU1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_smartconnect_0_0 || ORIG_REF_NAME==MercuryXU1_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/bd_1544.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_0/bd_1544_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_1/bd_1544_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_2/bd_1544_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_3/bd_1544_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_4/bd_1544_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_5/bd_1544_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_6/bd_1544_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_7/bd_1544_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_8/bd_1544_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_9/bd_1544_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_10/bd_1544_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_11/bd_1544_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_12/bd_1544_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_13/bd_1544_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_14/bd_1544_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_15/bd_1544_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_16/bd_1544_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_17/bd_1544_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_18/bd_1544_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_19/bd_1544_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_20/bd_1544_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_21/bd_1544_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_22/bd_1544_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_23/bd_1544_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_24/bd_1544_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_25/bd_1544_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_26/bd_1544_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_27/bd_1544_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_28/bd_1544_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_29/bd_1544_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_30/bd_1544_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_31/bd_1544_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_32/bd_1544_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_33/bd_1544_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_34/bd_1544_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_35/bd_1544_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_xbar_2/MercuryXU1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xbar_2 || ORIG_REF_NAME==MercuryXU1_xbar_2} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_interconnect_0_0/MercuryXU1_axis_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_interconnect_0_0 || ORIG_REF_NAME==MercuryXU1_axis_interconnect_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_100_0/MercuryXU1_proc_sys_reset_100_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_100_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_100_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_1/MercuryXU1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_1 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlslice_0_0/MercuryXU1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlslice_0_0 || ORIG_REF_NAME==MercuryXU1_xlslice_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlslice_0_1/MercuryXU1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlslice_0_1 || ORIG_REF_NAME==MercuryXU1_xlslice_0_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_300_0/MercuryXU1_proc_sys_reset_300_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_300_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_300_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/MercuryXU1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_ila_0_0 || ORIG_REF_NAME==MercuryXU1_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/bd_6493.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493 || ORIG_REF_NAME==bd_6493} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_0/bd_6493_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_ila_lib_0 || ORIG_REF_NAME==bd_6493_ila_lib_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_1/bd_6493_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_g_inst_0 || ORIG_REF_NAME==bd_6493_g_inst_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_2/bd_6493_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_1_aw_0 || ORIG_REF_NAME==bd_6493_slot_1_aw_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_3/bd_6493_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_1_w_0 || ORIG_REF_NAME==bd_6493_slot_1_w_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_4/bd_6493_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_1_b_0 || ORIG_REF_NAME==bd_6493_slot_1_b_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_5/bd_6493_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_1_ar_0 || ORIG_REF_NAME==bd_6493_slot_1_ar_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_6/bd_6493_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_1_r_0 || ORIG_REF_NAME==bd_6493_slot_1_r_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_7/bd_6493_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_2_aw_0 || ORIG_REF_NAME==bd_6493_slot_2_aw_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_8/bd_6493_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_2_w_0 || ORIG_REF_NAME==bd_6493_slot_2_w_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_9/bd_6493_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_2_b_0 || ORIG_REF_NAME==bd_6493_slot_2_b_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_10/bd_6493_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_2_ar_0 || ORIG_REF_NAME==bd_6493_slot_2_ar_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_11/bd_6493_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_2_r_0 || ORIG_REF_NAME==bd_6493_slot_2_r_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_12/bd_6493_slot_7_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_7_aw_0 || ORIG_REF_NAME==bd_6493_slot_7_aw_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_13/bd_6493_slot_7_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_7_w_0 || ORIG_REF_NAME==bd_6493_slot_7_w_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_14/bd_6493_slot_7_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_7_b_0 || ORIG_REF_NAME==bd_6493_slot_7_b_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_15/bd_6493_slot_7_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_7_ar_0 || ORIG_REF_NAME==bd_6493_slot_7_ar_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_16/bd_6493_slot_7_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6493_slot_7_r_0 || ORIG_REF_NAME==bd_6493_slot_7_r_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/MercuryXU1_system_ila_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_ila_0_2 || ORIG_REF_NAME==MercuryXU1_system_ila_0_2} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/bd_a512.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a512 || ORIG_REF_NAME==bd_a512} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/ip/ip_0/bd_a512_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a512_ila_lib_0 || ORIG_REF_NAME==bd_a512_ila_lib_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlslice_1_0/MercuryXU1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlslice_1_0 || ORIG_REF_NAME==MercuryXU1_xlslice_1_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/MercuryXU1_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_system_ila_0_3 || ORIG_REF_NAME==MercuryXU1_system_ila_0_3} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/bd_65d3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_65d3 || ORIG_REF_NAME==bd_65d3} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/ip/ip_0/bd_65d3_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/ip/ip_1/bd_65d3_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_65d3_g_inst_0 || ORIG_REF_NAME==bd_65d3_g_inst_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_tlast_generator_0_0/MercuryXU1_tlast_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_tlast_generator_0_0 || ORIG_REF_NAME==MercuryXU1_tlast_generator_0_0} -quiet] -quiet

# IP: ip/c_shift_ram_0/c_shift_ram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_2/MercuryXU1_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_2 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlslice_1_1/MercuryXU1_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlslice_1_1 || ORIG_REF_NAME==MercuryXU1_xlslice_1_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_clock_converter_0_0/MercuryXU1_axis_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_clock_converter_0_0 || ORIG_REF_NAME==MercuryXU1_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/MercuryXU1_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_smartconnect_0_1 || ORIG_REF_NAME==MercuryXU1_smartconnect_0_1} -quiet] -quiet

# Block Designs: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/bd_d585.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_0/bd_d585_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_1/bd_d585_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_2/bd_d585_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_3/bd_d585_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_4/bd_d585_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_5/bd_d585_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_6/bd_d585_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_7/bd_d585_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_8/bd_d585_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_9/bd_d585_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_10/bd_d585_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_11/bd_d585_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_12/bd_d585_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_13/bd_d585_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_14/bd_d585_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_15/bd_d585_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_16/bd_d585_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_17/bd_d585_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_18/bd_d585_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_19/bd_d585_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_20/bd_d585_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_21/bd_d585_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_22/bd_d585_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_23/bd_d585_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_24/bd_d585_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_25/bd_d585_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_26/bd_d585_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_27/bd_d585_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_28/bd_d585_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_29/bd_d585_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_1/MercuryXU1_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_1 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_clock_converter_0_1/MercuryXU1_axis_clock_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_clock_converter_0_1 || ORIG_REF_NAME==MercuryXU1_axis_clock_converter_0_1} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_tlast_generator_0_1/MercuryXU1_tlast_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_tlast_generator_0_1 || ORIG_REF_NAME==MercuryXU1_tlast_generator_0_1} -quiet] -quiet

# IP: ip/c_shift_ram_0/c_shift_ram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_0_0/MercuryXU1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_data_fifo_0_0 || ORIG_REF_NAME==MercuryXU1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_xlslice_2_0/MercuryXU1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_xlslice_2_0 || ORIG_REF_NAME==MercuryXU1_xlslice_2_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_stream_multiplexer_0_0/MercuryXU1_stream_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_stream_multiplexer_0_0 || ORIG_REF_NAME==MercuryXU1_stream_multiplexer_0_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_sample_number_0/MercuryXU1_axi_gpio_sample_number_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_sample_number_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_sample_number_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_1_0/MercuryXU1_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_axis_data_fifo_1_0 || ORIG_REF_NAME==MercuryXU1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_pc_0/MercuryXU1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_pc_0 || ORIG_REF_NAME==MercuryXU1_auto_pc_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_s_arb_req_suppress_concat_0/MercuryXU1_s_arb_req_suppress_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==MercuryXU1_s_arb_req_suppress_concat_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_s00_regslice_0/MercuryXU1_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_s00_regslice_0 || ORIG_REF_NAME==MercuryXU1_s00_regslice_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_s00_data_fifo_0/MercuryXU1_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_s00_data_fifo_0 || ORIG_REF_NAME==MercuryXU1_s00_data_fifo_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_s01_regslice_0/MercuryXU1_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_s01_regslice_0 || ORIG_REF_NAME==MercuryXU1_s01_regslice_0} -quiet] -quiet

# IP: bd/MercuryXU1/ip/MercuryXU1_auto_ss_k_0/MercuryXU1_auto_ss_k_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryXU1_auto_ss_k_0 || ORIG_REF_NAME==MercuryXU1_auto_ss_k_0} -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_0/MercuryXU1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_0_0/MercuryXU1_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_0_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_zynq_ultra_ps_e_0_0/MercuryXU1_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==MercuryXU1_zynq_ultra_ps_e_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_xbar_1/MercuryXU1_xbar_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_system_management_wiz_0_0 || ORIG_REF_NAME==MercuryXU1_system_management_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_0 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_1/bd_1544_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_1/bd_1544_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_2/bd_1544_arsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_3/bd_1544_rsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_4/bd_1544_awsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_5/bd_1544_wsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_6/bd_1544_bsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_10/bd_1544_s00a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_11/bd_1544_sarn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_12/bd_1544_srn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_13/bd_1544_sawn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_14/bd_1544_swn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_15/bd_1544_sbn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_19/bd_1544_s01a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_20/bd_1544_sarn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_21/bd_1544_srn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_25/bd_1544_s02a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_26/bd_1544_sawn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_27/bd_1544_swn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_28/bd_1544_sbn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_29/bd_1544_m00s2a_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_30/bd_1544_m00arn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_31/bd_1544_m00rn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_32/bd_1544_m00awn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_33/bd_1544_m00wn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/bd_0/ip/ip_34/bd_1544_m00bn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_0/ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_xbar_2/MercuryXU1_xbar_2_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_100_0/MercuryXU1_proc_sys_reset_100_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_100_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_100_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_100_0/MercuryXU1_proc_sys_reset_100_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_100_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_100_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_100_0/MercuryXU1_proc_sys_reset_100_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_1/MercuryXU1_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_1 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_1/MercuryXU1_axi_gpio_0_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_1/MercuryXU1_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_1 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_300_0/MercuryXU1_proc_sys_reset_300_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_300_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_300_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_300_0/MercuryXU1_proc_sys_reset_300_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_proc_sys_reset_300_0 || ORIG_REF_NAME==MercuryXU1_proc_sys_reset_300_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_proc_sys_reset_300_0/MercuryXU1_proc_sys_reset_300_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6493_ila_lib_0 || ORIG_REF_NAME==bd_6493_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6493_ila_lib_0 || ORIG_REF_NAME==bd_6493_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/ip/ip_0/bd_6493_ila_lib_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/bd_0/bd_6493_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_0/MercuryXU1_system_ila_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a512_ila_lib_0 || ORIG_REF_NAME==bd_a512_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a512_ila_lib_0 || ORIG_REF_NAME==bd_a512_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/ip/ip_0/bd_a512_ila_lib_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/bd_0/bd_a512_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_2/MercuryXU1_system_ila_0_2_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/ip/ip_0/bd_65d3_ila_lib_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/bd_0/bd_65d3_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_system_ila_0_3/MercuryXU1_system_ila_0_3_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_tlast_generator_0_0/MercuryXU1_tlast_generator_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_2/MercuryXU1_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_2 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_2/MercuryXU1_axi_gpio_0_2_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_0_2/MercuryXU1_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_0_2 || ORIG_REF_NAME==MercuryXU1_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axis_clock_converter_0_0/MercuryXU1_axis_clock_converter_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_1/bd_d585_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_1/bd_d585_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_2/bd_d585_arsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_3/bd_d585_rsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_4/bd_d585_awsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_5/bd_d585_wsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_6/bd_d585_bsw_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_10/bd_d585_s00a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_11/bd_d585_sarn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_12/bd_d585_srn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_13/bd_d585_sawn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_14/bd_d585_swn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_15/bd_d585_sbn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_19/bd_d585_s01a2s_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_20/bd_d585_sawn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_21/bd_d585_swn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_22/bd_d585_sbn_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_23/bd_d585_m00s2a_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_24/bd_d585_m00arn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_25/bd_d585_m00rn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_26/bd_d585_m00awn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_27/bd_d585_m00wn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/bd_0/ip/ip_28/bd_d585_m00bn_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_smartconnect_0_1/ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_1/MercuryXU1_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_1 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_1/MercuryXU1_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_dma_0_1 || ORIG_REF_NAME==MercuryXU1_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_1/MercuryXU1_axi_dma_0_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axis_clock_converter_0_1/MercuryXU1_axis_clock_converter_0_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_tlast_generator_0_1/MercuryXU1_tlast_generator_0_1_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_0_0/MercuryXU1_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_sample_number_0/MercuryXU1_axi_gpio_sample_number_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_sample_number_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_sample_number_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_sample_number_0/MercuryXU1_axi_gpio_sample_number_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_axi_gpio_sample_number_0/MercuryXU1_axi_gpio_sample_number_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_axi_gpio_sample_number_0 || ORIG_REF_NAME==MercuryXU1_axi_gpio_sample_number_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_axis_data_fifo_1_0/MercuryXU1_axis_data_fifo_1_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_auto_pc_0/MercuryXU1_auto_pc_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_s00_regslice_0/MercuryXU1_s00_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_s00_regslice_0 || ORIG_REF_NAME==MercuryXU1_s00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_s00_regslice_0/MercuryXU1_s00_regslice_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_s00_data_fifo_0/MercuryXU1_s00_data_fifo_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_s01_regslice_0/MercuryXU1_s01_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MercuryXU1_s01_regslice_0 || ORIG_REF_NAME==MercuryXU1_s01_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MercuryXU1/ip/MercuryXU1_s01_regslice_0/MercuryXU1_s01_regslice_0_ooc.xdc

# XDC: bd/MercuryXU1/ip/MercuryXU1_auto_ss_k_0/MercuryXU1_auto_ss_k_0_ooc.xdc

# XDC: bd/MercuryXU1/MercuryXU1_ooc.xdc
