# -------------------------------------------------------------------------------------------------
# -- Project          : Mercury+ XU1 Reference Design
# -- File description : Pin assignment and timing constraints file for Mercury PE1
# -- File name        : MercuryXU1_PE1.xdc
# -- Author           : Diana Ungureanu
# -------------------------------------------------------------------------------------------------
# -- Copyright (c) 2018 by Enclustra GmbH, Switzerland. All rights are reserved.
# -- Unauthorized duplication of this document, in whole or in part, by any means is prohibited
# -- without the prior written permission of Enclustra GmbH, Switzerland.
# --
# -- Although Enclustra GmbH believes that the information included in this publication is correct
# -- as of the date of publication, Enclustra GmbH reserves the right to make changes at any time
# -- without notice.
# --
# -- All information in this document may only be published by Enclustra GmbH, Switzerland.
# -------------------------------------------------------------------------------------------------
# -- Notes:
# -- The IO standards might need to be adapted to your design
# -------------------------------------------------------------------------------------------------
# -- File history:
# --
# -- Version | Date       | Author             | Remarks
# -- ----------------------------------------------------------------------------------------------
# -- 1.0     | 22.12.2016 | D. Ungureanu       | First released version
# -- 2.0     | 20.10.2017 | D. Ungureanu       | Consistency checks
# -- 3.0     | 11.06.2018 | D. Ungureanu       | Consistency checks
# --
# -------------------------------------------------------------------------------------------------

set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]

# ----------------------------------------------------------------------------------
# Important! Do not remove this constraint!
# This property ensures that all unused pins are set to high impedance.
# If the constraint is removed, all unused pins have to be set to HiZ in the top level file.
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
# ----------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------
# LEDs
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AE8 [get_ports Led2_N]
set_property IOSTANDARD LVCMOS18 [get_ports Led2_N]

# -------------------------------------------------------------------------------------------------
# I2C on PL side
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN V3 [get_ports I2c_Scl]
set_property IOSTANDARD LVCMOS18 [get_ports I2c_Scl]

set_property PACKAGE_PIN Y7 [get_ports I2c_Sda]
set_property IOSTANDARD LVCMOS18 [get_ports I2c_Sda]

# -------------------------------------------------------------------------------------------------
# bank 64
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AG4 [get_ports IO_B64_AG4]
set_property PACKAGE_PIN AG9 [get_ports IO_B64_AG9]
set_property PACKAGE_PIN AH11 [get_ports IO_B64_AH11]
set_property PACKAGE_PIN AJ1 [get_ports IO_B64_AJ1]
set_property PACKAGE_PIN AK8 [get_ports FPGA_SDATA]
set_property PACKAGE_PIN AK9 [get_ports SEL0]
set_property PACKAGE_PIN AH7 [get_ports SMA_TRIG]
set_property PACKAGE_PIN AJ7 [get_ports IO_B64_L11_GC_AJ7_N]
set_property PACKAGE_PIN AG8 [get_ports SEL4]
set_property PACKAGE_PIN AH8 [get_ports SEL3]
set_property PACKAGE_PIN AG6 [get_ports ADC3_DB1_p]
set_property PACKAGE_PIN AG5 [get_ports ADC3_DB1_n]
set_property PACKAGE_PIN AH6 [get_ports ADC4_DC1_p]
set_property PACKAGE_PIN AJ6 [get_ports ADC4_DC1_n]
set_property PACKAGE_PIN AK7 [get_ports ADC3_DA0_p]
set_property PACKAGE_PIN AK6 [get_ports ADC3_DA0_n]
set_property PACKAGE_PIN AF6 [get_ports ADC4_DD1_p]
set_property PACKAGE_PIN AF5 [get_ports ADC4_DD1_n]
set_property PACKAGE_PIN AJ5 [get_ports ADC4_DD0_p]
set_property PACKAGE_PIN AK5 [get_ports ADC4_DD0_n]
set_property PACKAGE_PIN AH4 [get_ports ADC4_DC0_p]
set_property PACKAGE_PIN AJ4 [get_ports ADC4_DC0_n]
set_property PACKAGE_PIN AK4 [get_ports ADC3_DA1_p]
set_property PACKAGE_PIN AK3 [get_ports ADC3_DA1_n]
set_property PACKAGE_PIN AF11 [get_ports RJ45_LVDS_TRIG_p]
set_property PACKAGE_PIN AG11 [get_ports RJ45_LVDS_TRIG_n]
set_property PACKAGE_PIN AH3 [get_ports ADC3_DB0_p]
set_property PACKAGE_PIN AH2 [get_ports ADC3_DB0_n]
set_property PACKAGE_PIN AJ2 [get_ports ADC4_FCLK_p]
set_property PACKAGE_PIN AK2 [get_ports ADC4_FCLK_n]
set_property PACKAGE_PIN AG1 [get_ports ADC4_DB1_p]
set_property PACKAGE_PIN AH1 [get_ports ADC4_DB1_n]
set_property PACKAGE_PIN AF3 [get_ports ADC3_FCLK_p]
set_property PACKAGE_PIN AG3 [get_ports ADC3_FCLK_n]
set_property PACKAGE_PIN AF2 [get_ports ADC4_DB0_p]
set_property PACKAGE_PIN AF1 [get_ports ADC4_DB0_n]
set_property PACKAGE_PIN AG13 [get_ports IO_B64_L2_AG13_P]
set_property PACKAGE_PIN AH13 [get_ports IO_B64_L2_AH13_N]
set_property PACKAGE_PIN AH12 [get_ports UART_SEL_0]
set_property PACKAGE_PIN AJ12 [get_ports UART_SEL_1]
set_property PACKAGE_PIN AK12 [get_ports SMA_CLK]
set_property PACKAGE_PIN AK13 [get_ports UART_SEL_4]
set_property PACKAGE_PIN AJ11 [get_ports UART_SEL_2]
set_property PACKAGE_PIN AK11 [get_ports UART_SEL_3]
set_property PACKAGE_PIN AJ10 [get_ports FPGA_SCLK]
set_property PACKAGE_PIN AK10 [get_ports FPGA_SDOUT]
set_property PACKAGE_PIN AF7 [get_ports SEL5]
set_property PACKAGE_PIN AF8 [get_ports SEL6]
set_property PACKAGE_PIN AF10 [get_ports MAX10_SPARE1]
set_property PACKAGE_PIN AG10 [get_ports MAX10_SPARE0]
set_property PACKAGE_PIN AH9 [get_ports SEL2]
set_property PACKAGE_PIN AJ9 [get_ports SEL1]

set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_AG4]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_AG9]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_AH11]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_AJ1]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_SDATA]
set_property IOSTANDARD LVCMOS18 [get_ports SEL0]
set_property IOSTANDARD LVCMOS18 [get_ports SMA_TRIG]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_L11_GC_AJ7_N]
set_property IOSTANDARD LVCMOS18 [get_ports SEL4]
set_property IOSTANDARD LVCMOS18 [get_ports SEL3]
set_property IOSTANDARD LVDS [get_ports ADC3_DB1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DB1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DC1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DC1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DA0_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DA0_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DD1_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DD1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DD0_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DD0_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DC0_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DC0_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DA1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DA1_p]
set_property IOSTANDARD LVDS [get_ports RJ45_LVDS_TRIG_p]
set_property IOSTANDARD LVDS [get_ports RJ45_LVDS_TRIG_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DB0_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DB0_p]
set_property IOSTANDARD LVDS [get_ports ADC4_FCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC4_FCLK_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DB1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DB1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_FCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC3_FCLK_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DB0_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DB0_p]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_L2_AG13_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B64_L2_AH13_N]
set_property IOSTANDARD LVCMOS18 [get_ports UART_SEL_0]
set_property IOSTANDARD LVCMOS18 [get_ports UART_SEL_1]
set_property IOSTANDARD LVCMOS18 [get_ports SMA_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports UART_SEL_4]
set_property IOSTANDARD LVCMOS18 [get_ports UART_SEL_2]
set_property IOSTANDARD LVCMOS18 [get_ports UART_SEL_3]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_SDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports SEL5]
set_property IOSTANDARD LVCMOS18 [get_ports SEL6]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE1]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE0]
set_property IOSTANDARD LVCMOS18 [get_ports SEL2]
set_property IOSTANDARD LVCMOS18 [get_ports SEL1]

# -------------------------------------------------------------------------------------------------
# bank 65
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AE1 [get_ports ADC3_DD1_n]
set_property PACKAGE_PIN AE7 [get_ports ADC3_DD1_p]
set_property PACKAGE_PIN AA8 [get_ports ADC1_DC1_p]
set_property PACKAGE_PIN AA7 [get_ports ADC1_DC1_n]
set_property PACKAGE_PIN AC7 [get_ports ADC4_DCLK_p]
set_property PACKAGE_PIN AD7 [get_ports ADC4_DCLK_n]
set_property PACKAGE_PIN AB8 [get_ports ADC1_DCLK_p]
set_property PACKAGE_PIN AC8 [get_ports ADC1_DCLK_n]
set_property PACKAGE_PIN AB6 [get_ports ADC0_DC1_p]
set_property PACKAGE_PIN AB5 [get_ports ADC0_DC1_n]
set_property PACKAGE_PIN AC6 [get_ports ADC0_DB0_p]
set_property PACKAGE_PIN AD6 [get_ports ADC0_DB0_n]
set_property PACKAGE_PIN AA6 [get_ports ADC0_DD1_p]
set_property PACKAGE_PIN AA5 [get_ports ADC0_DD1_n]
set_property PACKAGE_PIN AD5 [get_ports ADC1_DA1_p]
set_property PACKAGE_PIN AE5 [get_ports ADC1_DA1_n]
set_property PACKAGE_PIN AD4 [get_ports ADC1_DB0_p]
set_property PACKAGE_PIN AE4 [get_ports ADC1_DB0_n]
set_property PACKAGE_PIN AB4 [get_ports ADC1_DA0_p]
set_property PACKAGE_PIN AC4 [get_ports ADC1_DA0_n]
set_property PACKAGE_PIN AB3 [get_ports ADC0_DB1_p]
set_property PACKAGE_PIN AC3 [get_ports ADC0_DB1_n]
set_property PACKAGE_PIN AB13 [get_ports ADC3_DC0_p]
set_property PACKAGE_PIN AC13 [get_ports ADC3_DC0_n]
set_property PACKAGE_PIN AE3 [get_ports ADC0_DD0_p]
set_property PACKAGE_PIN AE2 [get_ports ADC0_DD0_n]
set_property PACKAGE_PIN AC2 [get_ports ADC0_DC0_p]
set_property PACKAGE_PIN AD2 [get_ports ADC0_DC0_n]
set_property PACKAGE_PIN AC1 [get_ports ADC0_FCLK_p]
set_property PACKAGE_PIN AD1 [get_ports ADC0_FCLK_n]
set_property PACKAGE_PIN AA3 [get_ports ADC0_DA0_p]
set_property PACKAGE_PIN AA2 [get_ports ADC0_DA0_n]
set_property PACKAGE_PIN AA1 [get_ports ADC0_DA1_p]
set_property PACKAGE_PIN AB1 [get_ports ADC0_DA1_n]
set_property PACKAGE_PIN AE13 [get_ports ADC3_DC1_p]
set_property PACKAGE_PIN AF13 [get_ports ADC3_DC1_n]
set_property PACKAGE_PIN AD12 [get_ports ADC3_DD0_p]
set_property PACKAGE_PIN AE12 [get_ports ADC3_DD0_n]
set_property PACKAGE_PIN AC11 [get_ports ADC4_DA1_p]
set_property PACKAGE_PIN AD11 [get_ports ADC4_DA1_n]
set_property PACKAGE_PIN AA12 [get_ports ADC4_DA0_p]
set_property PACKAGE_PIN AA11 [get_ports ADC4_DA0_n]
set_property PACKAGE_PIN AB11 [get_ports ADC1_DD0_p]
set_property PACKAGE_PIN AB10 [get_ports ADC1_DD0_n]
set_property PACKAGE_PIN AB9 [get_ports ADC1_DC0_p]
set_property PACKAGE_PIN AC9 [get_ports ADC1_DC0_n]
set_property PACKAGE_PIN AD10 [get_ports ADC1_DB1_p]
set_property PACKAGE_PIN AE10 [get_ports ADC1_DB1_n]
set_property PACKAGE_PIN AD9 [get_ports ADC1_FCLK_p]
set_property PACKAGE_PIN AE9 [get_ports ADC1_FCLK_n]

set_property IOSTANDARD LVDS [get_ports ADC3_DD1_p]
set_property IOSTANDARD LVDS [get_ports ADC3_DD1_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DC1_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DC1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DCLK_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DCLK_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DC1_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DC1_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DB0_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DB0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DD1_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DD1_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DA1_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DA1_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DB0_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DB0_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DA0_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DA0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DB1_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DB1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DC0_p]
set_property IOSTANDARD LVDS [get_ports ADC3_DC0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DD0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DD0_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DC0_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DC0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_FCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC0_FCLK_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DA0_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DA0_p]
set_property IOSTANDARD LVDS [get_ports ADC0_DA1_n]
set_property IOSTANDARD LVDS [get_ports ADC0_DA1_p]
set_property IOSTANDARD LVDS [get_ports ADC3_DC1_p]
set_property IOSTANDARD LVDS [get_ports ADC3_DC1_n]
set_property IOSTANDARD LVDS [get_ports ADC3_DD0_p]
set_property IOSTANDARD LVDS [get_ports ADC3_DD0_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DA1_p]
set_property IOSTANDARD LVDS [get_ports ADC4_DA1_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DA0_n]
set_property IOSTANDARD LVDS [get_ports ADC4_DA0_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DD0_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DD0_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DC0_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DC0_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DB1_p]
set_property IOSTANDARD LVDS [get_ports ADC1_DB1_n]
set_property IOSTANDARD LVDS [get_ports ADC1_FCLK_p]
set_property IOSTANDARD LVDS [get_ports ADC1_FCLK_n]

# -------------------------------------------------------------------------------------------------
# bank 66
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN U6 [get_ports ADC1_SEN]
set_property PACKAGE_PIN U7 [get_ports ADC0_SEN]
set_property PACKAGE_PIN V6 [get_ports MAX10_SPARE6]
set_property PACKAGE_PIN V7 [get_ports MAX10_SPARE7]
set_property PACKAGE_PIN W7 [get_ports ADC1_DD1_p]
set_property PACKAGE_PIN W6 [get_ports ADC1_DD1_n]
set_property PACKAGE_PIN U8 [get_ports IO_B66_L13_GC_U8_P]
set_property PACKAGE_PIN V8 [get_ports IO_B66_L13_GC_V8_N]
set_property PACKAGE_PIN Y8 [get_ports IO_B66_L14_GC_Y8_N]
set_property PACKAGE_PIN Y9 [get_ports IO_B66_L14_GC_Y9_P]
set_property PACKAGE_PIN U11 [get_ports IO_B66_L15_AD11_U11_P]
set_property PACKAGE_PIN V11 [get_ports IO_B66_L15_AD11_V11_N]
set_property PACKAGE_PIN W10 [get_ports IO_B66_L16_AD3_W10_N]
set_property PACKAGE_PIN W11 [get_ports IO_B66_L16_AD3_W11_P]
set_property PACKAGE_PIN U9 [get_ports IO_B66_L17_AD10_U9_P]
set_property PACKAGE_PIN V9 [get_ports IO_B66_L17_AD10_V9_N]
set_property PACKAGE_PIN T11 [get_ports IO_B66_L18_AD2_T11_P]
set_property PACKAGE_PIN U10 [get_ports IO_B66_L18_AD2_U10_N]
set_property PACKAGE_PIN T10 [get_ports IO_B66_L19_AD9_T10_N]
set_property PACKAGE_PIN R10 [get_ports IO_B66_L19_AD9_R10_P]
set_property PACKAGE_PIN Y3 [get_ports MAX10_SPARE2]
set_property PACKAGE_PIN Y4 [get_ports MAX10_SPARE4]
set_property PACKAGE_PIN P10 [get_ports IO_B66_L20_AD1_P10_N]
set_property PACKAGE_PIN P11 [get_ports IO_B66_L20_AD1_P11_P]
set_property PACKAGE_PIN M12 [get_ports IO_B66_L21_AD8_M12_N]
set_property PACKAGE_PIN N12 [get_ports IO_B66_L21_AD8_N12_P]
set_property PACKAGE_PIN M10 [get_ports IO_B66_L22_AD0_M10_N]
set_property PACKAGE_PIN N10 [get_ports IO_B66_L22_AD0_N10_P]
set_property PACKAGE_PIN L11 [get_ports IO_B66_L23_L11_N]
set_property PACKAGE_PIN L12 [get_ports IO_B66_L23_L12_P]
set_property PACKAGE_PIN K10 [get_ports IO_B66_L24_K10_N]
set_property PACKAGE_PIN L10 [get_ports IO_B66_L24_L10_P]
set_property PACKAGE_PIN Y1 [get_ports MAX10_SPARE3]
set_property PACKAGE_PIN Y2 [get_ports MAX10_SPARE5]
set_property PACKAGE_PIN W1 [get_ports MAX10_SPARE8]
set_property PACKAGE_PIN W2 [get_ports MAX10_SPARE9]
set_property PACKAGE_PIN V1 [get_ports MAX10_SPARE10]
set_property PACKAGE_PIN V2 [get_ports IO_B66_L4_AD7_V2_P]
set_property PACKAGE_PIN U2 [get_ports MAX10_SPARE13]
set_property PACKAGE_PIN U3 [get_ports MAX10_SPARE12]
set_property PACKAGE_PIN T1 [get_ports ADC3_SEN]
set_property PACKAGE_PIN U1 [get_ports ADC4_SEN]
set_property PACKAGE_PIN W5 [get_ports ADC_PDN]
set_property PACKAGE_PIN Y5 [get_ports ADC_RST]
set_property PACKAGE_PIN V4 [get_ports ADC_SDOUT]
set_property PACKAGE_PIN W4 [get_ports ADC2_SEN]
set_property PACKAGE_PIN U4 [get_ports ADC_SDATA]
set_property PACKAGE_PIN U5 [get_ports ADC_SCLK]
set_property PACKAGE_PIN N11 [get_ports IO_B66_N11]
set_property PACKAGE_PIN Y10 [get_ports IO_B66_Y10]

set_property IOSTANDARD LVCMOS18 [get_ports ADC1_SEN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC0_SEN]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE6]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE7]
set_property IOSTANDARD LVDS [get_ports ADC1_DD1_n]
set_property IOSTANDARD LVDS [get_ports ADC1_DD1_p]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L13_GC_U8_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L13_GC_V8_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L14_GC_Y8_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L14_GC_Y9_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L15_AD11_U11_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L15_AD11_V11_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L16_AD3_W10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L16_AD3_W11_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L17_AD10_U9_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L17_AD10_V9_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L18_AD2_T11_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L18_AD2_U10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L19_AD9_T10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L19_AD9_R10_P]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE2]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE4]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L20_AD1_P10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L20_AD1_P11_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L21_AD8_M12_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L21_AD8_N12_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L22_AD0_M10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L22_AD0_N10_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L23_L11_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L23_L12_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L24_K10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L24_L10_P]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE3]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE5]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE8]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE9]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE10]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_L4_AD7_V2_P]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE13]
set_property IOSTANDARD LVCMOS18 [get_ports MAX10_SPARE12]
set_property IOSTANDARD LVCMOS18 [get_ports ADC3_SEN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC4_SEN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_PDN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_RST]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_SDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_SEN]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_SDATA]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_N11]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B66_Y10]


# -------------------------------------------------------------------------------------------------
# bank 48
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN G11 [get_ports ADC2_DD1_n]
set_property PACKAGE_PIN H12 [get_ports ADC2_DD1_p]
set_property PACKAGE_PIN H11 [get_ports ADC2_DD0_n]
set_property PACKAGE_PIN J12 [get_ports ADC2_DD0_p]
set_property PACKAGE_PIN J10 [get_ports ADC2_DC1_n]
set_property PACKAGE_PIN J11 [get_ports ADC2_DC1_p]
set_property PACKAGE_PIN B11 [get_ports IO_B48_L1_AD15_B11_N]
set_property PACKAGE_PIN C12 [get_ports IO_B48_L1_AD15_C12_P]
set_property PACKAGE_PIN A11 [get_ports IO_B48_L2_AD14_A11_N]
set_property PACKAGE_PIN A12 [get_ports IO_B48_L2_AD14_A12_P]
set_property PACKAGE_PIN A10 [get_ports IO_B48_L3_AD13_A10_N]
set_property PACKAGE_PIN B10 [get_ports IO_B48_L3_AD13_B10_P]
set_property PACKAGE_PIN C11 [get_ports IO_B48_L4_AD12_C11_N]
set_property PACKAGE_PIN D11 [get_ports IO_B48_L4_AD12_D11_P]
set_property PACKAGE_PIN D12 [get_ports IO_B48_L5_HDGC_D12_N]
set_property PACKAGE_PIN E12 [get_ports IO_B48_L5_HDGC_E12_P]
set_property PACKAGE_PIN D10 [get_ports IO_B48_L6_HDGC_D10_N]
set_property PACKAGE_PIN E10 [get_ports IO_B48_L6_HDGC_E10_P]
set_property PACKAGE_PIN F11 [get_ports ADC2_FCLK_n]
set_property PACKAGE_PIN F12 [get_ports ADC2_FCLK_p]
set_property PACKAGE_PIN F10 [get_ports PEO_LVDS_TRIG_n]
set_property PACKAGE_PIN G10 [get_ports PEO_LVDS_TRIG_p]
set_property PACKAGE_PIN K12 [get_ports ADC2_DC0_n]
set_property PACKAGE_PIN K13 [get_ports ADC2_DC0_p]

set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DD1_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DD1_p]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DD0_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DD0_p]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DC1_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DC1_p]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L1_AD15_B11_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L1_AD15_C12_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L2_AD14_A11_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L2_AD14_A12_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L3_AD13_A10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L3_AD13_B10_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L4_AD12_C11_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L4_AD12_D11_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L5_HDGC_D12_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L5_HDGC_E12_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L6_HDGC_D10_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B48_L6_HDGC_E10_P]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_FCLK_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_FCLK_p]
set_property IOSTANDARD LVCMOS18 [get_ports PEO_LVDS_TRIG_n]
set_property IOSTANDARD LVCMOS18 [get_ports PEO_LVDS_TRIG_p]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DC0_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DC0_p]

# -------------------------------------------------------------------------------------------------
# bank 47
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN J15 [get_ports ADC2_DB0_n]
set_property PACKAGE_PIN K15 [get_ports ADC2_DB0_p]
set_property PACKAGE_PIN J14 [get_ports LVDS_SMA_RJ45_CLK1_N]
set_property PACKAGE_PIN K14 [get_ports LVDS_SMA_RJ45_CLK1_P]
set_property PACKAGE_PIN H13 [get_ports IO_B47_L12_AD0_H13_N]
set_property PACKAGE_PIN H14 [get_ports IO_B47_L12_AD0_H14_P]
set_property PACKAGE_PIN A15 [get_ports IO_B47_L1_AD11_A15_N]
set_property PACKAGE_PIN B15 [get_ports IO_B47_L1_AD11_B15_P]
set_property PACKAGE_PIN A14 [get_ports IO_B47_L2_AD10_A14_N]
set_property PACKAGE_PIN B14 [get_ports IO_B47_L2_AD10_B14_P]
set_property PACKAGE_PIN A13 [get_ports IO_B47_L3_AD9_A13_N]
set_property PACKAGE_PIN B13 [get_ports IO_B47_L3_AD9_B13_P]
set_property PACKAGE_PIN C13 [get_ports IO_B47_L4_AD8_C13_N]
set_property PACKAGE_PIN C14 [get_ports IO_B47_L4_AD8_C14_P]
set_property PACKAGE_PIN D14 [get_ports ADC2_DCLK_n]
set_property PACKAGE_PIN D15 [get_ports ADC2_DCLK_p]
set_property PACKAGE_PIN E13 [get_ports IO_B47_L6_HDGC_AD6_E13_N]
set_property PACKAGE_PIN E14 [get_ports IO_B47_L6_HDGC_AD6_E14_P]
set_property PACKAGE_PIN E15 [get_ports ADC2_DA0_n]
set_property PACKAGE_PIN F15 [get_ports ADC2_DA0_p]
set_property PACKAGE_PIN F13 [get_ports ADC2_DB1_n]
set_property PACKAGE_PIN G13 [get_ports ADC2_DB1_p]
set_property PACKAGE_PIN G14 [get_ports ADC2_DA1_n]
set_property PACKAGE_PIN G15 [get_ports ADC2_DA1_p]

set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DB0_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DB0_p]
set_property IOSTANDARD LVCMOS18 [get_ports LVDS_SMA_RJ45_CLK1_N]
set_property IOSTANDARD LVCMOS18 [get_ports LVDS_SMA_RJ45_CLK1_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L12_AD0_H13_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L12_AD0_H14_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L1_AD11_A15_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L1_AD11_B15_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L2_AD10_A14_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L2_AD10_B14_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L3_AD9_A13_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L3_AD9_B13_P]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L4_AD8_C13_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L4_AD8_C14_P]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DCLK_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DCLK_p]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L6_HDGC_AD6_E13_N]
set_property IOSTANDARD LVCMOS18 [get_ports IO_B47_L6_HDGC_AD6_E14_P]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DA0_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DA0_p]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DB1_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DB1_p]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DA1_n]
set_property IOSTANDARD LVCMOS18 [get_ports ADC2_DA1_p]

## #LVDS example
##set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_D12_N}]
##set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_E12_P}]
##set_property PACKAGE_PIN D11  [get_ports {IO_B48_L4_AD12_D11_P}]

# -------------------------------------------------------------------------------------------------
# Termination Styles
# -------------------------------------------------------------------------------------------------

set_property DIFF_TERM_ADV TERM_100 [get_ports RJ45_LVDS_TRIG_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_FCLK_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DD1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DD0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DC1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DC0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DB1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DB0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DA1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DA0_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC1_DCLK_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_FCLK_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DD1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DD0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DC1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DC0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DB1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DB0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DA1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC0_DA0_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DCLK_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_FCLK_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DD1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DD0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DC1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DC0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DB1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DB0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DA1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC3_DA0_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_FCLK_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DD1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DD0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DC1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DC0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DB1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DB0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DA1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports ADC4_DA0_p]

# -------------------------------------------------------------------------------------------------
# clocking
# -------------------------------------------------------------------------------------------------
create_clock -period 2.667 -name clkin1 -add [get_ports ADC1_DCLK_p]

# -------------------------------------------------------------------------------------------------
# PS banks defined in the block design
# -------------------------------------------------------------------------------------------------

set_property DONT_TOUCH true [get_nets debug_adc_spi_ss]

set_property MARK_DEBUG true [get_nets ADC0_SEN_OBUF]
set_property MARK_DEBUG true [get_nets ADC1_SEN_OBUF]
set_property MARK_DEBUG true [get_nets ADC2_SEN_OBUF]
set_property MARK_DEBUG true [get_nets ADC3_SEN_OBUF]
set_property MARK_DEBUG true [get_nets ADC4_SEN_OBUF]
set_property mark_debug true [get_nets MercuryXU1_i/adc_ss_en]
set_property MARK_DEBUG true [get_nets MercuryXU1_i/ps_master_i2c_sda_o]
set_property MARK_DEBUG true [get_nets MercuryXU1_i/ps_master_i2c_scl_o]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_0]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_2]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_4]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_7]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_9]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_10]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_13]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in1_in]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_5]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_6]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_11]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_1]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_14]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in0_in]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in3_in]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_3]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_8]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_12]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in2_in]
set_property MARK_DEBUG true [get_nets MercuryXU1_i/ps_spi_0_io1_o]
set_property MARK_DEBUG true [get_nets MercuryXU1_i/ps_spi_0_io0_o]
set_property MARK_DEBUG true [get_nets MercuryXU1_i/ps_spi_0_sck_o]

set_property MARK_DEBUG true [get_nets adc_b64_sample_clock]
set_property MARK_DEBUG true [get_nets adc_b64_pll_dclk_p]
set_property MARK_DEBUG true [get_nets adc_b64_pll_dclk_n]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[5]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[5]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[5]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[9]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[8]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[10]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[11]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[2]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[5]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[4]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[6]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[5]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[7]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[0]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[3]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[1]}]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[5]}]


connect_debug_port dbg_hub/clk [get_nets u_ila_1_pl_clk0]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list serdes_clock_b65/inst/clk_out4_b65_62p5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {adc0_dd_pardata_j1[0][0]} {adc0_dd_pardata_j1[0][1]} {adc0_dd_pardata_j1[0][2]} {adc0_dd_pardata_j1[0][3]} {adc0_dd_pardata_j1[0][4]} {adc0_dd_pardata_j1[0][5]} {adc0_dd_pardata_j1[0][6]} {adc0_dd_pardata_j1[0][7]} {adc0_dd_pardata_j1[0][8]} {adc0_dd_pardata_j1[0][9]} {adc0_dd_pardata_j1[0][10]} {adc0_dd_pardata_j1[0][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {adc0_db_pardata_j3[1][0]} {adc0_db_pardata_j3[1][1]} {adc0_db_pardata_j3[1][2]} {adc0_db_pardata_j3[1][3]} {adc0_db_pardata_j3[1][4]} {adc0_db_pardata_j3[1][5]} {adc0_db_pardata_j3[1][6]} {adc0_db_pardata_j3[1][7]} {adc0_db_pardata_j3[1][8]} {adc0_db_pardata_j3[1][9]} {adc0_db_pardata_j3[1][10]} {adc0_db_pardata_j3[1][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {adc0_dd_pardata_j1[1][0]} {adc0_dd_pardata_j1[1][1]} {adc0_dd_pardata_j1[1][2]} {adc0_dd_pardata_j1[1][3]} {adc0_dd_pardata_j1[1][4]} {adc0_dd_pardata_j1[1][5]} {adc0_dd_pardata_j1[1][6]} {adc0_dd_pardata_j1[1][7]} {adc0_dd_pardata_j1[1][8]} {adc0_dd_pardata_j1[1][9]} {adc0_dd_pardata_j1[1][10]} {adc0_dd_pardata_j1[1][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {adc0_da_pardata_j4[0][0]} {adc0_da_pardata_j4[0][1]} {adc0_da_pardata_j4[0][2]} {adc0_da_pardata_j4[0][3]} {adc0_da_pardata_j4[0][4]} {adc0_da_pardata_j4[0][5]} {adc0_da_pardata_j4[0][6]} {adc0_da_pardata_j4[0][7]} {adc0_da_pardata_j4[0][8]} {adc0_da_pardata_j4[0][9]} {adc0_da_pardata_j4[0][10]} {adc0_da_pardata_j4[0][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 12 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {adc0_dc_pardata_j2[0][0]} {adc0_dc_pardata_j2[0][1]} {adc0_dc_pardata_j2[0][2]} {adc0_dc_pardata_j2[0][3]} {adc0_dc_pardata_j2[0][4]} {adc0_dc_pardata_j2[0][5]} {adc0_dc_pardata_j2[0][6]} {adc0_dc_pardata_j2[0][7]} {adc0_dc_pardata_j2[0][8]} {adc0_dc_pardata_j2[0][9]} {adc0_dc_pardata_j2[0][10]} {adc0_dc_pardata_j2[0][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 12 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {adc0_dc_pardata_j2[1][0]} {adc0_dc_pardata_j2[1][1]} {adc0_dc_pardata_j2[1][2]} {adc0_dc_pardata_j2[1][3]} {adc0_dc_pardata_j2[1][4]} {adc0_dc_pardata_j2[1][5]} {adc0_dc_pardata_j2[1][6]} {adc0_dc_pardata_j2[1][7]} {adc0_dc_pardata_j2[1][8]} {adc0_dc_pardata_j2[1][9]} {adc0_dc_pardata_j2[1][10]} {adc0_dc_pardata_j2[1][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 12 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {adc0_da_pardata_j4[1][0]} {adc0_da_pardata_j4[1][1]} {adc0_da_pardata_j4[1][2]} {adc0_da_pardata_j4[1][3]} {adc0_da_pardata_j4[1][4]} {adc0_da_pardata_j4[1][5]} {adc0_da_pardata_j4[1][6]} {adc0_da_pardata_j4[1][7]} {adc0_da_pardata_j4[1][8]} {adc0_da_pardata_j4[1][9]} {adc0_da_pardata_j4[1][10]} {adc0_da_pardata_j4[1][11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {adc0_db_pardata_j3[0][0]} {adc0_db_pardata_j3[0][1]} {adc0_db_pardata_j3[0][2]} {adc0_db_pardata_j3[0][3]} {adc0_db_pardata_j3[0][4]} {adc0_db_pardata_j3[0][5]} {adc0_db_pardata_j3[0][6]} {adc0_db_pardata_j3[0][7]} {adc0_db_pardata_j3[0][8]} {adc0_db_pardata_j3[0][9]} {adc0_db_pardata_j3[0][10]} {adc0_db_pardata_j3[0][11]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list MercuryXU1_i/MercuryXU1_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list ADC0_SEN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list ADC1_SEN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list ADC2_SEN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list ADC3_SEN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list ADC4_SEN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list ADC_PDN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list ADC_RST_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list MercuryXU1_i/ps_spi_0_io0_o]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list MercuryXU1_i/ps_spi_0_io1_o]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list MercuryXU1_i/ps_spi_0_sck_o]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_1]
