# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen.xci
# IP: The module: 'adc_sample_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen.xci
# IP: The module: 'adc_sample_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/adc_sample_clk_gen/adc_sample_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_sample_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
