set_property SRC_FILE_INFO {cfile:/home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/clk_wiz_1_b64_b66_pll/clk_wiz_1_b64_b66_pll/clk_wiz_1_b64_b66_pll_in_context.xdc rfile:../../../NuPRISM.srcs/sources_1/ip/clk_wiz_1_b64_b66_pll/clk_wiz_1_b64_b66_pll/clk_wiz_1_b64_b66_pll_in_context.xdc id:1 order:EARLY scoped_inst:serdes_clock_b64} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/ip/clk_wiz_0_b65_mmcm/clk_wiz_0_b65_mmcm/clk_wiz_0_b65_mmcm_in_context.xdc rfile:../../../NuPRISM.srcs/sources_1/ip/clk_wiz_0_b65_mmcm/clk_wiz_0_b65_mmcm/clk_wiz_0_b65_mmcm_in_context.xdc id:2 order:EARLY scoped_inst:serdes_clock_b65} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xdc rfile:../../../NuPRISM.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0_1/MercuryXU1_system_management_wiz_0_0.xdc id:3 order:EARLY scoped_inst:MercuryXU1_i/MercuryXU1_i/system_management_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xdc rfile:../../../NuPRISM.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_axi_dma_0_0/MercuryXU1_axi_dma_0_0.xdc id:4 order:EARLY scoped_inst:MercuryXU1_i/MercuryXU1_i/axi_dma_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/Source/iwcd-xu1-petalinux-rev0-2020-01/Vivado_NuPRISM/NuPRISM/NuPRISM.srcs/MercuryNuPRISM/imports/src/MercuryXU1_NuPRISM.xdc rfile:../../../NuPRISM.srcs/MercuryNuPRISM/imports/src/MercuryXU1_NuPRISM.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:6 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:7 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:8 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:9 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:10 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:11 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:12 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:13 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:14 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:15 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:16 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:17 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:18 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:19 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:20 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:21 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[0].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:22 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[1].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:23 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[2].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:24 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:25 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:26 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:27 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:28 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:29 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:30 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:31 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:32 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:33 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:34 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:35 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:36 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:37 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/edev/tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../tools/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:38 order:LATE scoped_inst:{MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
current_instance serdes_clock_b64
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 6.668 13.335} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
current_instance serdes_clock_b65
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.667 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 6.668 13.335} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
current_instance MercuryXU1_i/MercuryXU1_i/system_management_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD ANALOG [get_ports  vp]
set_property src_info {type:SCOPED_XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD ANALOG [get_ports  vn]
set_property src_info {type:SCOPED_XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SYSMONE4_X0Y0 [get_cells -hier {*inst_sysmon} -filter {NAME =~ *inst_sysmon}]
current_instance
current_instance MercuryXU1_i/MercuryXU1_i/axi_dma_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
set_property src_info {type:XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8 [get_ports Led2_N]
set_property src_info {type:XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports I2c_Scl]
set_property src_info {type:XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports I2c_Sda]
set_property src_info {type:XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG4 [get_ports IO_B64_AG4]
set_property src_info {type:XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9 [get_ports IO_B64_AG9]
set_property src_info {type:XDC file:5 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11 [get_ports IO_B64_AH11]
set_property src_info {type:XDC file:5 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ1 [get_ports IO_B64_AJ1]
set_property src_info {type:XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8 [get_ports FPGA_SDATA]
set_property src_info {type:XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK9 [get_ports SEL0]
set_property src_info {type:XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7 [get_ports SMA_TRIG]
set_property src_info {type:XDC file:5 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ7 [get_ports IO_B64_L11_GC_AJ7_N]
set_property src_info {type:XDC file:5 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG8 [get_ports SEL4]
set_property src_info {type:XDC file:5 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8 [get_ports SEL3]
set_property src_info {type:XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG6 [get_ports ADC3_DB1_p]
set_property src_info {type:XDC file:5 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG5 [get_ports ADC3_DB1_n]
set_property src_info {type:XDC file:5 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6 [get_ports ADC4_DC1_p]
set_property src_info {type:XDC file:5 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6 [get_ports ADC4_DC1_n]
set_property src_info {type:XDC file:5 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK7 [get_ports ADC3_DA0_p]
set_property src_info {type:XDC file:5 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK6 [get_ports ADC3_DA0_n]
set_property src_info {type:XDC file:5 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF6 [get_ports ADC4_DD1_p]
set_property src_info {type:XDC file:5 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports ADC4_DD1_n]
set_property src_info {type:XDC file:5 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ5 [get_ports ADC4_DD0_p]
set_property src_info {type:XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK5 [get_ports ADC4_DD0_n]
set_property src_info {type:XDC file:5 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4 [get_ports ADC4_DC0_p]
set_property src_info {type:XDC file:5 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ4 [get_ports ADC4_DC0_n]
set_property src_info {type:XDC file:5 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK4 [get_ports ADC3_DA1_p]
set_property src_info {type:XDC file:5 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK3 [get_ports ADC3_DA1_n]
set_property src_info {type:XDC file:5 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11 [get_ports RJ45_LVDS_TRIG_p]
set_property src_info {type:XDC file:5 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11 [get_ports RJ45_LVDS_TRIG_n]
set_property src_info {type:XDC file:5 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH3 [get_ports ADC3_DB0_p]
set_property src_info {type:XDC file:5 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2 [get_ports ADC3_DB0_n]
set_property src_info {type:XDC file:5 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ2 [get_ports ADC4_FCLK_p]
set_property src_info {type:XDC file:5 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK2 [get_ports ADC4_FCLK_n]
set_property src_info {type:XDC file:5 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG1 [get_ports ADC4_DB1_p]
set_property src_info {type:XDC file:5 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1 [get_ports ADC4_DB1_n]
set_property src_info {type:XDC file:5 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3 [get_ports ADC3_FCLK_p]
set_property src_info {type:XDC file:5 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG3 [get_ports ADC3_FCLK_n]
set_property src_info {type:XDC file:5 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2 [get_ports ADC4_DB0_p]
set_property src_info {type:XDC file:5 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1 [get_ports ADC4_DB0_n]
set_property src_info {type:XDC file:5 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG13 [get_ports IO_B64_L2_AG13_P]
set_property src_info {type:XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports IO_B64_L2_AH13_N]
set_property src_info {type:XDC file:5 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12 [get_ports UART_SEL_0]
set_property src_info {type:XDC file:5 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ12 [get_ports UART_SEL_1]
set_property src_info {type:XDC file:5 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK12 [get_ports SMA_CLK]
set_property src_info {type:XDC file:5 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports UART_SEL_4]
set_property src_info {type:XDC file:5 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ11 [get_ports UART_SEL_2]
set_property src_info {type:XDC file:5 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK11 [get_ports UART_SEL_3]
set_property src_info {type:XDC file:5 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ10 [get_ports FPGA_SCLK]
set_property src_info {type:XDC file:5 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK10 [get_ports FPGA_SDOUT]
set_property src_info {type:XDC file:5 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7 [get_ports SEL5]
set_property src_info {type:XDC file:5 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports SEL6]
set_property src_info {type:XDC file:5 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports MAX10_SPARE1]
set_property src_info {type:XDC file:5 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10 [get_ports MAX10_SPARE0]
set_property src_info {type:XDC file:5 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9 [get_ports SEL2]
set_property src_info {type:XDC file:5 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ9 [get_ports SEL1]
set_property src_info {type:XDC file:5 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1 [get_ports ADC3_DD1_n]
set_property src_info {type:XDC file:5 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE7 [get_ports ADC3_DD1_p]
set_property src_info {type:XDC file:5 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports ADC1_DC1_p]
set_property src_info {type:XDC file:5 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports ADC1_DC1_n]
set_property src_info {type:XDC file:5 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7 [get_ports ADC4_DCLK_p]
set_property src_info {type:XDC file:5 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD7 [get_ports ADC4_DCLK_n]
set_property src_info {type:XDC file:5 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports ADC1_DCLK_p]
set_property src_info {type:XDC file:5 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8 [get_ports ADC1_DCLK_n]
set_property src_info {type:XDC file:5 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports ADC0_DC1_p]
set_property src_info {type:XDC file:5 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports ADC0_DC1_n]
set_property src_info {type:XDC file:5 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6 [get_ports ADC0_DB0_p]
set_property src_info {type:XDC file:5 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6 [get_ports ADC0_DB0_n]
set_property src_info {type:XDC file:5 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6 [get_ports ADC0_DD1_p]
set_property src_info {type:XDC file:5 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5 [get_ports ADC0_DD1_n]
set_property src_info {type:XDC file:5 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5 [get_ports ADC1_DA1_p]
set_property src_info {type:XDC file:5 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports ADC1_DA1_n]
set_property src_info {type:XDC file:5 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4 [get_ports ADC1_DB0_p]
set_property src_info {type:XDC file:5 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE4 [get_ports ADC1_DB0_n]
set_property src_info {type:XDC file:5 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports ADC1_DA0_p]
set_property src_info {type:XDC file:5 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4 [get_ports ADC1_DA0_n]
set_property src_info {type:XDC file:5 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB3 [get_ports ADC0_DB1_p]
set_property src_info {type:XDC file:5 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3 [get_ports ADC0_DB1_n]
set_property src_info {type:XDC file:5 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13 [get_ports ADC3_DC0_p]
set_property src_info {type:XDC file:5 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports ADC3_DC0_n]
set_property src_info {type:XDC file:5 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3 [get_ports ADC0_DD0_p]
set_property src_info {type:XDC file:5 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2 [get_ports ADC0_DD0_n]
set_property src_info {type:XDC file:5 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2 [get_ports ADC0_DC0_p]
set_property src_info {type:XDC file:5 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2 [get_ports ADC0_DC0_n]
set_property src_info {type:XDC file:5 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports ADC0_FCLK_p]
set_property src_info {type:XDC file:5 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1 [get_ports ADC0_FCLK_n]
set_property src_info {type:XDC file:5 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3 [get_ports ADC0_DA0_p]
set_property src_info {type:XDC file:5 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA2 [get_ports ADC0_DA0_n]
set_property src_info {type:XDC file:5 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA1 [get_ports ADC0_DA1_p]
set_property src_info {type:XDC file:5 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports ADC0_DA1_n]
set_property src_info {type:XDC file:5 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports ADC3_DC1_p]
set_property src_info {type:XDC file:5 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports ADC3_DC1_n]
set_property src_info {type:XDC file:5 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports ADC3_DD0_p]
set_property src_info {type:XDC file:5 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12 [get_ports ADC3_DD0_n]
set_property src_info {type:XDC file:5 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11 [get_ports ADC4_DA1_p]
set_property src_info {type:XDC file:5 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports ADC4_DA1_n]
set_property src_info {type:XDC file:5 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports ADC4_DA0_p]
set_property src_info {type:XDC file:5 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports ADC4_DA0_n]
set_property src_info {type:XDC file:5 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports ADC1_DD0_p]
set_property src_info {type:XDC file:5 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports ADC1_DD0_n]
set_property src_info {type:XDC file:5 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports ADC1_DC0_p]
set_property src_info {type:XDC file:5 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports ADC1_DC0_n]
set_property src_info {type:XDC file:5 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10 [get_ports ADC1_DB1_p]
set_property src_info {type:XDC file:5 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10 [get_ports ADC1_DB1_n]
set_property src_info {type:XDC file:5 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9 [get_ports ADC1_FCLK_p]
set_property src_info {type:XDC file:5 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE9 [get_ports ADC1_FCLK_n]
set_property src_info {type:XDC file:5 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports ADC1_SEN]
set_property src_info {type:XDC file:5 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports ADC0_SEN]
set_property src_info {type:XDC file:5 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports MAX10_SPARE6]
set_property src_info {type:XDC file:5 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports MAX10_SPARE7]
set_property src_info {type:XDC file:5 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports ADC1_DD1_p]
set_property src_info {type:XDC file:5 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports ADC1_DD1_n]
set_property src_info {type:XDC file:5 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports IO_B66_L13_GC_U8_P]
set_property src_info {type:XDC file:5 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports IO_B66_L13_GC_V8_N]
set_property src_info {type:XDC file:5 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports IO_B66_L14_GC_Y8_N]
set_property src_info {type:XDC file:5 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports IO_B66_L14_GC_Y9_P]
set_property src_info {type:XDC file:5 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11 [get_ports IO_B66_L15_AD11_U11_P]
set_property src_info {type:XDC file:5 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports IO_B66_L15_AD11_V11_N]
set_property src_info {type:XDC file:5 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports IO_B66_L16_AD3_W10_N]
set_property src_info {type:XDC file:5 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11 [get_ports IO_B66_L16_AD3_W11_P]
set_property src_info {type:XDC file:5 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports IO_B66_L17_AD10_U9_P]
set_property src_info {type:XDC file:5 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports IO_B66_L17_AD10_V9_N]
set_property src_info {type:XDC file:5 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports IO_B66_L18_AD2_T11_P]
set_property src_info {type:XDC file:5 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10 [get_ports IO_B66_L18_AD2_U10_N]
set_property src_info {type:XDC file:5 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports IO_B66_L19_AD9_T10_N]
set_property src_info {type:XDC file:5 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10 [get_ports IO_B66_L19_AD9_R10_P]
set_property src_info {type:XDC file:5 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports MAX10_SPARE2]
set_property src_info {type:XDC file:5 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y4 [get_ports MAX10_SPARE4]
set_property src_info {type:XDC file:5 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10 [get_ports IO_B66_L20_AD1_P10_N]
set_property src_info {type:XDC file:5 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P11 [get_ports IO_B66_L20_AD1_P11_P]
set_property src_info {type:XDC file:5 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12 [get_ports IO_B66_L21_AD8_M12_N]
set_property src_info {type:XDC file:5 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N12 [get_ports IO_B66_L21_AD8_N12_P]
set_property src_info {type:XDC file:5 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M10 [get_ports IO_B66_L22_AD0_M10_N]
set_property src_info {type:XDC file:5 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N10 [get_ports IO_B66_L22_AD0_N10_P]
set_property src_info {type:XDC file:5 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L11 [get_ports IO_B66_L23_L11_N]
set_property src_info {type:XDC file:5 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports IO_B66_L23_L12_P]
set_property src_info {type:XDC file:5 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10 [get_ports IO_B66_L24_K10_N]
set_property src_info {type:XDC file:5 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10 [get_ports IO_B66_L24_L10_P]
set_property src_info {type:XDC file:5 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports MAX10_SPARE3]
set_property src_info {type:XDC file:5 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2 [get_ports MAX10_SPARE5]
set_property src_info {type:XDC file:5 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1 [get_ports MAX10_SPARE8]
set_property src_info {type:XDC file:5 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W2 [get_ports MAX10_SPARE9]
set_property src_info {type:XDC file:5 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports MAX10_SPARE10]
set_property src_info {type:XDC file:5 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports IO_B66_L4_AD7_V2_P]
set_property src_info {type:XDC file:5 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports MAX10_SPARE13]
set_property src_info {type:XDC file:5 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports MAX10_SPARE12]
set_property src_info {type:XDC file:5 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports ADC3_SEN]
set_property src_info {type:XDC file:5 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports ADC4_SEN]
set_property src_info {type:XDC file:5 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports ADC_PDN]
set_property src_info {type:XDC file:5 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports ADC_RST]
set_property src_info {type:XDC file:5 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports ADC_SDOUT]
set_property src_info {type:XDC file:5 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports ADC2_SEN]
set_property src_info {type:XDC file:5 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports ADC_SDATA]
set_property src_info {type:XDC file:5 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports ADC_SCLK]
set_property src_info {type:XDC file:5 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports IO_B66_N11]
set_property src_info {type:XDC file:5 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports IO_B66_Y10]
set_property src_info {type:XDC file:5 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11 [get_ports ADC2_DD1_n]
set_property src_info {type:XDC file:5 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports ADC2_DD1_p]
set_property src_info {type:XDC file:5 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports ADC2_DD0_n]
set_property src_info {type:XDC file:5 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12 [get_ports ADC2_DD0_p]
set_property src_info {type:XDC file:5 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports ADC2_DC1_n]
set_property src_info {type:XDC file:5 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports ADC2_DC1_p]
set_property src_info {type:XDC file:5 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports IO_B48_L1_AD15_B11_N]
set_property src_info {type:XDC file:5 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports IO_B48_L1_AD15_C12_P]
set_property src_info {type:XDC file:5 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11 [get_ports IO_B48_L2_AD14_A11_N]
set_property src_info {type:XDC file:5 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports IO_B48_L2_AD14_A12_P]
set_property src_info {type:XDC file:5 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports IO_B48_L3_AD13_A10_N]
set_property src_info {type:XDC file:5 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports IO_B48_L3_AD13_B10_P]
set_property src_info {type:XDC file:5 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports IO_B48_L4_AD12_C11_N]
set_property src_info {type:XDC file:5 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports IO_B48_L4_AD12_D11_P]
set_property src_info {type:XDC file:5 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports IO_B48_L5_HDGC_D12_N]
set_property src_info {type:XDC file:5 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports IO_B48_L5_HDGC_E12_P]
set_property src_info {type:XDC file:5 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports IO_B48_L6_HDGC_D10_N]
set_property src_info {type:XDC file:5 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports IO_B48_L6_HDGC_E10_P]
set_property src_info {type:XDC file:5 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports ADC2_FCLK_n]
set_property src_info {type:XDC file:5 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports ADC2_FCLK_p]
set_property src_info {type:XDC file:5 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports PEO_LVDS_TRIG_n]
set_property src_info {type:XDC file:5 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports PEO_LVDS_TRIG_p]
set_property src_info {type:XDC file:5 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports ADC2_DC0_n]
set_property src_info {type:XDC file:5 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports ADC2_DC0_p]
set_property src_info {type:XDC file:5 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports ADC2_DB0_n]
set_property src_info {type:XDC file:5 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports ADC2_DB0_p]
set_property src_info {type:XDC file:5 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports LVDS_SMA_RJ45_CLK1_N]
set_property src_info {type:XDC file:5 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports LVDS_SMA_RJ45_CLK1_P]
set_property src_info {type:XDC file:5 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports IO_B47_L12_AD0_H13_N]
set_property src_info {type:XDC file:5 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports IO_B47_L12_AD0_H14_P]
set_property src_info {type:XDC file:5 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports IO_B47_L1_AD11_A15_N]
set_property src_info {type:XDC file:5 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports IO_B47_L1_AD11_B15_P]
set_property src_info {type:XDC file:5 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports IO_B47_L2_AD10_A14_N]
set_property src_info {type:XDC file:5 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports IO_B47_L2_AD10_B14_P]
set_property src_info {type:XDC file:5 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports IO_B47_L3_AD9_A13_N]
set_property src_info {type:XDC file:5 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B13 [get_ports IO_B47_L3_AD9_B13_P]
set_property src_info {type:XDC file:5 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports IO_B47_L4_AD8_C13_N]
set_property src_info {type:XDC file:5 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports IO_B47_L4_AD8_C14_P]
set_property src_info {type:XDC file:5 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports ADC2_DCLK_n]
set_property src_info {type:XDC file:5 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports ADC2_DCLK_p]
set_property src_info {type:XDC file:5 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports IO_B47_L6_HDGC_AD6_E13_N]
set_property src_info {type:XDC file:5 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports IO_B47_L6_HDGC_AD6_E14_P]
set_property src_info {type:XDC file:5 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports ADC2_DA0_n]
set_property src_info {type:XDC file:5 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports ADC2_DA0_p]
set_property src_info {type:XDC file:5 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports ADC2_DB1_n]
set_property src_info {type:XDC file:5 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports ADC2_DB1_p]
set_property src_info {type:XDC file:5 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports ADC2_DA1_n]
set_property src_info {type:XDC file:5 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports ADC2_DA1_p]
set_property src_info {type:XDC file:5 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_nets debug_adc_spi_ss]
set_property src_info {type:XDC file:5 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ADC0_SEN_OBUF]
set_property src_info {type:XDC file:5 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ADC1_SEN_OBUF]
set_property src_info {type:XDC file:5 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ADC2_SEN_OBUF]
set_property src_info {type:XDC file:5 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ADC3_SEN_OBUF]
set_property src_info {type:XDC file:5 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ADC4_SEN_OBUF]
set_property src_info {type:XDC file:5 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/adc_ss_en]
set_property src_info {type:XDC file:5 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_0]
set_property src_info {type:XDC file:5 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_2]
set_property src_info {type:XDC file:5 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_4]
set_property src_info {type:XDC file:5 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_7]
set_property src_info {type:XDC file:5 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_9]
set_property src_info {type:XDC file:5 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_10]
set_property src_info {type:XDC file:5 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_13]
set_property src_info {type:XDC file:5 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in1_in]
set_property src_info {type:XDC file:5 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_5]
set_property src_info {type:XDC file:5 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_6]
set_property src_info {type:XDC file:5 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_11]
set_property src_info {type:XDC file:5 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_1]
set_property src_info {type:XDC file:5 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_14]
set_property src_info {type:XDC file:5 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in0_in]
set_property src_info {type:XDC file:5 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in]
set_property src_info {type:XDC file:5 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in3_in]
set_property src_info {type:XDC file:5 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_3]
set_property src_info {type:XDC file:5 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_8]
set_property src_info {type:XDC file:5 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/MercuryXU1_i_n_12]
set_property src_info {type:XDC file:5 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets MercuryXU1_i/p_0_in2_in]
set_property src_info {type:XDC file:5 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[7]}]
set_property src_info {type:XDC file:5 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[2]}]
set_property src_info {type:XDC file:5 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[10]}]
set_property src_info {type:XDC file:5 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[6]}]
set_property src_info {type:XDC file:5 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[5]}]
set_property src_info {type:XDC file:5 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[0]}]
set_property src_info {type:XDC file:5 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[9]}]
set_property src_info {type:XDC file:5 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[4]}]
set_property src_info {type:XDC file:5 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[10]}]
set_property src_info {type:XDC file:5 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[8]}]
set_property src_info {type:XDC file:5 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[1]}]
set_property src_info {type:XDC file:5 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[5]}]
set_property src_info {type:XDC file:5 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[9]}]
set_property src_info {type:XDC file:5 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[11]}]
set_property src_info {type:XDC file:5 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[8]}]
set_property src_info {type:XDC file:5 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[11]}]
set_property src_info {type:XDC file:5 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[7]}]
set_property src_info {type:XDC file:5 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[1]}]
set_property src_info {type:XDC file:5 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[10]}]
set_property src_info {type:XDC file:5 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[9]}]
set_property src_info {type:XDC file:5 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[2]}]
set_property src_info {type:XDC file:5 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[0]}]
set_property src_info {type:XDC file:5 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[6]}]
set_property src_info {type:XDC file:5 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[6]}]
set_property src_info {type:XDC file:5 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[7]}]
set_property src_info {type:XDC file:5 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[0]}]
set_property src_info {type:XDC file:5 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[3]}]
set_property src_info {type:XDC file:5 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[1]}]
set_property src_info {type:XDC file:5 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[2]}]
set_property src_info {type:XDC file:5 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[0]}]
set_property src_info {type:XDC file:5 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[4]}]
set_property src_info {type:XDC file:5 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[3]}]
set_property src_info {type:XDC file:5 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[6]}]
set_property src_info {type:XDC file:5 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[5]}]
set_property src_info {type:XDC file:5 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[8]}]
set_property src_info {type:XDC file:5 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[9]}]
set_property src_info {type:XDC file:5 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[9]}]
set_property src_info {type:XDC file:5 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[2]}]
set_property src_info {type:XDC file:5 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[8]}]
set_property src_info {type:XDC file:5 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[10]}]
set_property src_info {type:XDC file:5 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[4]}]
set_property src_info {type:XDC file:5 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[9]}]
set_property src_info {type:XDC file:5 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[8]}]
set_property src_info {type:XDC file:5 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[8]}]
set_property src_info {type:XDC file:5 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[11]}]
set_property src_info {type:XDC file:5 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[11]}]
set_property src_info {type:XDC file:5 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[4]}]
set_property src_info {type:XDC file:5 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[0]}]
set_property src_info {type:XDC file:5 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[11]}]
set_property src_info {type:XDC file:5 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[10]}]
set_property src_info {type:XDC file:5 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[1]}]
set_property src_info {type:XDC file:5 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[10]}]
set_property src_info {type:XDC file:5 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[1]}]
set_property src_info {type:XDC file:5 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[3]}]
set_property src_info {type:XDC file:5 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[6]}]
set_property src_info {type:XDC file:5 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[11]}]
set_property src_info {type:XDC file:5 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[2]}]
set_property src_info {type:XDC file:5 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[3]}]
set_property src_info {type:XDC file:5 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[7]}]
set_property src_info {type:XDC file:5 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[2]}]
set_property src_info {type:XDC file:5 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[7]}]
set_property src_info {type:XDC file:5 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[3]}]
set_property src_info {type:XDC file:5 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[4]}]
set_property src_info {type:XDC file:5 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_8_out[5]}]
set_property src_info {type:XDC file:5 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[4]}]
set_property src_info {type:XDC file:5 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[6]}]
set_property src_info {type:XDC file:5 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_10_out[5]}]
set_property src_info {type:XDC file:5 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_0_out[7]}]
set_property src_info {type:XDC file:5 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_2_out[0]}]
set_property src_info {type:XDC file:5 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[3]}]
set_property src_info {type:XDC file:5 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_6_out[1]}]
set_property src_info {type:XDC file:5 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property mark_debug true [get_nets {Ad9229Core_b64/p_4_out[5]}]
set_property src_info {type:XDC file:5 line:662 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_pl_clk0]
set_property src_info {type:XDC file:5 line:665 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:5 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:5 line:675 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list serdes_clock_b65/inst/clk_out4_b65_62p5]]
set_property src_info {type:XDC file:5 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:5 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:5 line:678 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {adc0_da_pardata_j4[0][0]} {adc0_da_pardata_j4[0][1]} {adc0_da_pardata_j4[0][2]} {adc0_da_pardata_j4[0][3]} {adc0_da_pardata_j4[0][4]} {adc0_da_pardata_j4[0][5]} {adc0_da_pardata_j4[0][6]} {adc0_da_pardata_j4[0][7]} {adc0_da_pardata_j4[0][8]} {adc0_da_pardata_j4[0][9]} {adc0_da_pardata_j4[0][10]} {adc0_da_pardata_j4[0][11]}]]
set_property src_info {type:XDC file:5 line:679 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:5 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:5 line:682 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {adc0_da_pardata_j4[1][0]} {adc0_da_pardata_j4[1][1]} {adc0_da_pardata_j4[1][2]} {adc0_da_pardata_j4[1][3]} {adc0_da_pardata_j4[1][4]} {adc0_da_pardata_j4[1][5]} {adc0_da_pardata_j4[1][6]} {adc0_da_pardata_j4[1][7]} {adc0_da_pardata_j4[1][8]} {adc0_da_pardata_j4[1][9]} {adc0_da_pardata_j4[1][10]} {adc0_da_pardata_j4[1][11]}]]
set_property src_info {type:XDC file:5 line:683 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:5 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:5 line:686 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {adc0_dc_pardata_j2[0][0]} {adc0_dc_pardata_j2[0][1]} {adc0_dc_pardata_j2[0][2]} {adc0_dc_pardata_j2[0][3]} {adc0_dc_pardata_j2[0][4]} {adc0_dc_pardata_j2[0][5]} {adc0_dc_pardata_j2[0][6]} {adc0_dc_pardata_j2[0][7]} {adc0_dc_pardata_j2[0][8]} {adc0_dc_pardata_j2[0][9]} {adc0_dc_pardata_j2[0][10]} {adc0_dc_pardata_j2[0][11]}]]
set_property src_info {type:XDC file:5 line:687 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:5 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:5 line:690 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {adc0_db_pardata_j3[0][0]} {adc0_db_pardata_j3[0][1]} {adc0_db_pardata_j3[0][2]} {adc0_db_pardata_j3[0][3]} {adc0_db_pardata_j3[0][4]} {adc0_db_pardata_j3[0][5]} {adc0_db_pardata_j3[0][6]} {adc0_db_pardata_j3[0][7]} {adc0_db_pardata_j3[0][8]} {adc0_db_pardata_j3[0][9]} {adc0_db_pardata_j3[0][10]} {adc0_db_pardata_j3[0][11]}]]
set_property src_info {type:XDC file:5 line:691 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:5 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:5 line:694 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {adc0_db_pardata_j3[1][0]} {adc0_db_pardata_j3[1][1]} {adc0_db_pardata_j3[1][2]} {adc0_db_pardata_j3[1][3]} {adc0_db_pardata_j3[1][4]} {adc0_db_pardata_j3[1][5]} {adc0_db_pardata_j3[1][6]} {adc0_db_pardata_j3[1][7]} {adc0_db_pardata_j3[1][8]} {adc0_db_pardata_j3[1][9]} {adc0_db_pardata_j3[1][10]} {adc0_db_pardata_j3[1][11]}]]
set_property src_info {type:XDC file:5 line:695 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:5 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:5 line:698 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {adc0_dc_pardata_j2[1][0]} {adc0_dc_pardata_j2[1][1]} {adc0_dc_pardata_j2[1][2]} {adc0_dc_pardata_j2[1][3]} {adc0_dc_pardata_j2[1][4]} {adc0_dc_pardata_j2[1][5]} {adc0_dc_pardata_j2[1][6]} {adc0_dc_pardata_j2[1][7]} {adc0_dc_pardata_j2[1][8]} {adc0_dc_pardata_j2[1][9]} {adc0_dc_pardata_j2[1][10]} {adc0_dc_pardata_j2[1][11]}]]
set_property src_info {type:XDC file:5 line:699 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:5 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:5 line:702 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {adc0_dd_pardata_j1[0][0]} {adc0_dd_pardata_j1[0][1]} {adc0_dd_pardata_j1[0][2]} {adc0_dd_pardata_j1[0][3]} {adc0_dd_pardata_j1[0][4]} {adc0_dd_pardata_j1[0][5]} {adc0_dd_pardata_j1[0][6]} {adc0_dd_pardata_j1[0][7]} {adc0_dd_pardata_j1[0][8]} {adc0_dd_pardata_j1[0][9]} {adc0_dd_pardata_j1[0][10]} {adc0_dd_pardata_j1[0][11]}]]
set_property src_info {type:XDC file:5 line:703 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:5 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:5 line:706 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {adc0_dd_pardata_j1[1][0]} {adc0_dd_pardata_j1[1][1]} {adc0_dd_pardata_j1[1][2]} {adc0_dd_pardata_j1[1][3]} {adc0_dd_pardata_j1[1][4]} {adc0_dd_pardata_j1[1][5]} {adc0_dd_pardata_j1[1][6]} {adc0_dd_pardata_j1[1][7]} {adc0_dd_pardata_j1[1][8]} {adc0_dd_pardata_j1[1][9]} {adc0_dd_pardata_j1[1][10]} {adc0_dd_pardata_j1[1][11]}]]
set_property src_info {type:XDC file:5 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:708 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:710 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_1]
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[0].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[1].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[2].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:24 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:25 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:28 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:29 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:30 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:31 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:32 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:33 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:34 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:35 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s02_nodes/s02_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:36 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:37 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {MercuryXU1_i/MercuryXU1_i/axi_smc/inst/s01_nodes/s01_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:38 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
